### PR TITLE
BL-9514 Replace last updated with last uploaded

### PR DESCRIPTION
**Pull request by gmartin7**
* new info was in parsedb, so a bit trickier to get

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/321)

### CODE REVIEW

**Review by JohnThomson — CHANGES_REQUESTED** [review]
LGTM, but one more comment might help.

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/321#-:-MWih7S7AYAgT4jjJXCV:b-gfz5b6)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[src/model/Book.ts, line 200 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/321#-MWigxrj0rnebM4GEDZh:-MWigxrj0rnebM4GEDZi:b639hlz) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/cb7123d9631ec5dab6ef852ae017c07e7b55ac5c/src/model/Book.ts#L200)):*
> ```XML
>             const date = new Date(this.lastUploaded.iso);
>             this.lastUploadedDate =
>                 date < new Date(2020, 1, 11, 11) ? undefined : date;
> ```

Seems to need some explanation. Why are dates before this not useful? I'm guessing it is when we started sending this information, but if so, why would other books have anything at all? What about people who continued to use an older version of Bloom after that date? Or does the upload date come from some source other than Bloom desktop, like cloud code?

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/321)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/model/Book.ts, line 200 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/321#-MWigxrj0rnebM4GEDZh:-MWjJ-dL00gNqNk1ZqT1:bp430dl) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/cb7123d9631ec5dab6ef852ae017c07e7b55ac5c/src/model/Book.ts#L200)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Seems to need some explanation. Why are dates before this not useful? I'm guessing it is when we started sending this information, but if so, why would other books have anything at all? What about people who continued to use an older version of Bloom after that date? Or does the upload date come from some source other than Bloom desktop, like cloud code?
</blockquote></details>

Oh wow! Thanks for asking. I'm afraid I copied some code without really understanding it. This is much better. That date had to do with when harvester thumbnails became more reliable. Not relevant here.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/321)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @gmartin7 and @JohnThomson)

___
*[src/localization/Code Strings.json, line 223 at r2](https://reviewable.io/reviews/bloombooks/bloomlibrary2/321#-MWjKsqW5Cq3xnmXwhva:-MWjKsqW5Cq3xnmXwhvb:b-skxqbo) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/88d061fddb1823b79cbcecee709c936d772c4161/src/localization/Code Strings.json#L223)):*
> ```JSON
>     "book.metadata.lastUpdated": {
>         "description": "",
>         "message": "Last updated on {date}"
> ```

We should remove this obsolete one, right?

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/321)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[src/localization/Code Strings.json, line 223 at r2](https://reviewable.io/reviews/bloombooks/bloomlibrary2/321#-MWjKsqW5Cq3xnmXwhva:-MWjQ-Lp-yKH4ukkH293:b-896fix) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/88d061fddb1823b79cbcecee709c936d772c4161/src/localization/Code Strings.json#L223)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

We should remove this obsolete one, right?
</blockquote></details>

Done.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/321)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/321)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/model/Book.ts, line 200 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/321#-MWigxrj0rnebM4GEDZh:-MWjUEuS-1LmfCTdNZqr:b-896fix) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/cb7123d9631ec5dab6ef852ae017c07e7b55ac5c/src/model/Book.ts#L200)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Oh wow! Thanks for asking. I'm afraid I copied some code without really understanding it. This is much better. That date had to do with when harvester thumbnails became more reliable. Not relevant here.
</blockquote></details>

Done.

**Review by JohnThomson — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/321)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Pull request merged**
