### PR TITLE
Allow staff to request harvesting a book (BL-8287)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/302)

### CODE REVIEW

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/302)* status: all files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

___
*[src/components/Admin/StaffPanel.tsx, line 137 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/302#-MTb3jAW97malFbIH8PR:-MTb3jAW97malFbIH8PS:b-vhmmpy) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/3ba5d186cfe548cd231346af227bd6c0e3c9abd6/src/components/Admin/StaffPanel.tsx#L137)):*
> ```XML
>         }
>         return "";
>     };
> ```

What advantage does this recursive algorithm have over just a simple loop?
If this is better for some reason, we at least need a comment explaining what it is doing and what index is.
Also, it seems like it would be better to have index be optional and default to 0.
___
*[src/components/Admin/StaffPanel.tsx, line 434 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/302#-MTb438y1YYnT0STREOw:-MTb438y1YYnT0STREOx:b-zeo9ec) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/3ba5d186cfe548cd231346af227bd6c0e3c9abd6/src/components/Admin/StaffPanel.tsx#L434)):*
> ```
> apHarvester
> ```
What's the ap?
Could use a better id, I think. Or just remove the id?

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/302)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[src/components/Admin/StaffPanel.tsx, line 137 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/302#-MTb3jAW97malFbIH8PR:-MTbszLl8DUFl3iUQALC:b6tjsa5) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/3ba5d186cfe548cd231346af227bd6c0e3c9abd6/src/components/Admin/StaffPanel.tsx#L137)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

What advantage does this recursive algorithm have over just a simple loop?
If this is better for some reason, we at least need a comment explaining what it is doing and what index is.
Also, it seems like it would be better to have index be optional and default to 0.
</blockquote></details>

Sometimes my mind just thinks recursively?  I've changed to an iterative algorithm and added a method comment.
___
*[src/components/Admin/StaffPanel.tsx, line 434 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/302#-MTb438y1YYnT0STREOw:-MTbskzt0qrMk12JRgjd:b-2wj4tx) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/3ba5d186cfe548cd231346af227bd6c0e3c9abd6/src/components/Admin/StaffPanel.tsx#L434)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> apHarvester
> ```
What's the ap?
Could use a better id, I think. Or just remove the id?
</blockquote></details>

I deleted the id.  I don't see any need for it.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/302)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[src/components/Admin/StaffPanel.tsx, line 137 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/302#-MTb3jAW97malFbIH8PR:-MTc-AeMDYhVNJ4vajle:b-xw59y4) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/3ba5d186cfe548cd231346af227bd6c0e3c9abd6/src/components/Admin/StaffPanel.tsx#L137)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Sometimes my mind just thinks recursively?  I've changed to an iterative algorithm and added a method comment.
</blockquote></details>

I'll put this out there in case you think it is worth making a change, but feel free to merge.
A js idiom would look like 
```
log.map((l)=> <span>{l}</span>).join(<br/>)
```

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/302)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/components/Admin/StaffPanel.tsx, line 137 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/302#-MTb3jAW97malFbIH8PR:-MTfhAbqAMgGW51-z1jU:beyxgp0) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/3ba5d186cfe548cd231346af227bd6c0e3c9abd6/src/components/Admin/StaffPanel.tsx#L137)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'll put this out there in case you think it is worth making a change, but feel free to merge.
A js idiom would look like 
```
log.map((l)=> <span>{l}</span>).join(<br/>)
```
</blockquote></details>

I tried something like this initially, and discovered that .join() only allow strings as an argument.  It doesn't allow JSX elements.

**Pull request merged**
