### PR TITLE
BL-9263 Make Collection desc. scroll vertically

### PR DESCRIPTION
**Pull request by gmartin7**
* fixes Guatemala and Enabling Writers

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/223)

### CODE REVIEW

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/223)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[src/components/banners/Blurb.tsx, line 36 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/223#-MMuq9qJ2j2Br0PhLuw0:-MMuq9qJ2j2Br0PhLuw1:bxl93w0) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/5dfcf7099fe0e846953a3f551fb4827480fe18d7/src/components/banners/Blurb.tsx#L36)):*
> ```XML
>                     max-width: 600px;
>                     margin-bottom: 10px;
>                     overflow-x: hidden;
> ```

I don't know what it would take to get x overflow, but if we got it, we wouldn't want to clip?

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/223)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[src/components/banners/Blurb.tsx, line 36 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/223#-MMuq9qJ2j2Br0PhLuw0:-MMv7Kdc0e2xiLlK719P:b-eq8fp5) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/5dfcf7099fe0e846953a3f551fb4827480fe18d7/src/components/banners/Blurb.tsx#L36)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I don't know what it would take to get x overflow, but if we got it, we wouldn't want to clip?
</blockquote></details>

I tried just removing the rule and it didn't add the scroll bar where needed. This works fine, though.

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/223)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[src/components/banners/Blurb.tsx, line 36 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/223#-MMuq9qJ2j2Br0PhLuw0:-MMv7uwa-6mBkEKX0V0p:bewa8a9) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/5dfcf7099fe0e846953a3f551fb4827480fe18d7/src/components/banners/Blurb.tsx#L36)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

I tried just removing the rule and it didn't add the scroll bar where needed. This works fine, though.
</blockquote></details>

No, it's supposed to be overflow-y:scroll   we don't ever want the x to scroll.
You can see the difference if you make the screen really narrow.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/223)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[src/components/banners/Blurb.tsx, line 36 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/223#-MMuq9qJ2j2Br0PhLuw0:-MMv9XQO8wCmTPv_KKv9:b-1sh5o4) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/5dfcf7099fe0e846953a3f551fb4827480fe18d7/src/components/banners/Blurb.tsx#L36)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

No, it's supposed to be overflow-y:scroll   we don't ever want the x to scroll.
You can see the difference if you make the screen really narrow.
</blockquote></details>

overflow-y: scroll will make EVERY description have a scroll bar (See Covid-19 page). overflow-x: clip is ideal, but is not available in Chrome or early (<81) FF. We CAN use `overflow` with two keywords, however.

**Pull request merged**
