### PR TITLE
BL-9073 Get about page linked

### PR DESCRIPTION
**Pull request by gmartin7**
* link on Create page button now works

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/187)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/187)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[src/components/Routes.tsx, line 67 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/187#-MKvVIXr3jLjp0WdeLB8:-MKvVIXr3jLjp0WdeLB9:b-gldtm4) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/1cf440fb829a15d968f567dbe52c777ae59e5539/src/components/Routes.tsx#L67)):*
> ```XML
>                 >
>                     <Redirect to="/about" />
>                 </Route>
> ```

I don't understand why we would want this. Why not just have `/page/create/about` route to `<ContentfulMultiPartPage urlKey="new-about" />` ?
As it is, it will change the url and change from Create to Read along with the theme change (I think).

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/187)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/components/Routes.tsx, line 67 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/187#-MKvVIXr3jLjp0WdeLB8:-ML8pv5e2z5HKQbR1Lhk:b-i5ngdb) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/1cf440fb829a15d968f567dbe52c777ae59e5539/src/components/Routes.tsx#L67)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I don't understand why we would want this. Why not just have `/page/create/about` route to `<ContentfulMultiPartPage urlKey="new-about" />` ?
As it is, it will change the url and change from Create to Read along with the theme change (I think).
</blockquote></details>

Done. Also, I'm wondering... I had changed the order on the About page of the last two sections (Getting Started and Limitations). I think I had probably better put them back the way they were in the original.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/187)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/components/Routes.tsx, line 67 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/187#-MKvVIXr3jLjp0WdeLB8:-ML8rHt10_Zrl9ZHn8QH:bhbb1b4) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/1cf440fb829a15d968f567dbe52c777ae59e5539/src/components/Routes.tsx#L67)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Done. Also, I'm wondering... I had changed the order on the About page of the last two sections (Getting Started and Limitations). I think I had probably better put them back the way they were in the original.
</blockquote></details>

(Done.)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/187)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
