### PR TITLE
Grid: distinguish between read starts and finishes (BL-13994)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/572)

### CODE REVIEW

**Comment by andrew-polk** [comment]
*[`src/components/Grid/GridColumns.tsx` line 383 at r1](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/572#-OA-f4Z-BNosW6mVo7ny:-OA-f4Z-BNosW6mVo7nz:b-s7r5wl) ([raw file](https://github.com/BloomBooks/BloomLibrary2/blob/34840a4961799e5c51c2be816956d97b1eaaa870/src/components/Grid/GridColumns.tsx#L383)):*
> ```XML
>         },
>         {
>             name: "downloadsForTranslation",
> ```

This is setting the names back to what they were before Steve's change so people's saved settings for order and hidden columns are preserved.

**Comment by andrew-polk** [comment]
*[`src/components/Grid/GridColumns.tsx` line 404 at r1](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/572#-OA-fFCV-gt25wkDm1ee:-OA-fFCV-gt25wkDm1ef:b-bw5hok) ([raw file](https://github.com/BloomBooks/BloomLibrary2/blob/34840a4961799e5c51c2be816956d97b1eaaa870/src/components/Grid/GridColumns.tsx#L404)):*
> ```XML
>             if (b.name === "title") return 1;
>             return a.title!.localeCompare(b.title!);
>         });
> ```

I changed the order of map and sort so the sort would happen on title, not name.

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/572)* status: 0 of 3 files reviewed, all discussions resolved

___
*[`src/components/Grid/GridColumns.tsx` line 383 at r1](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/572#-OA-f4Z-BNosW6mVo7ny:-OA-fXF26634ou8xPMK9:bxclfb7) ([raw file](https://github.com/BloomBooks/BloomLibrary2/blob/34840a4961799e5c51c2be816956d97b1eaaa870/src/components/Grid/GridColumns.tsx#L383)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This is setting the names back to what they were before Steve's change so people's saved settings for order and hidden columns are preserved.
</blockquote></details>

I think that's ultra-low importance, unless they'd get an error? It would be higher if we were storing the config in the URL so that people had bookmarks for various reports.  Given that, would you rather have the other name?

**Review by hatton — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/572)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @andrew-polk)

**Review by StephenMcConnel — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/572#-:-OA-ggvMETLN-bwtl4gM:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @andrew-polk)

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/572)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @andrew-polk)

___
*[`src/components/Grid/GridColumns.tsx` line 383 at r1](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/572#-OA-f4Z-BNosW6mVo7ny:-OA-gIJr5QTXWMaCwX6l:bmnhlg1) ([raw file](https://github.com/BloomBooks/BloomLibrary2/blob/34840a4961799e5c51c2be816956d97b1eaaa870/src/components/Grid/GridColumns.tsx#L383)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I think that's ultra-low importance, unless they'd get an error? It would be higher if we were storing the config in the URL so that people had bookmarks for various reports.  Given that, would you rather have the other name?
</blockquote></details>

I don't see much advantage to the new names.
In fact, if it wasn't for compatibility, I would just make them all match the title as the rest of them do.

**Comment by andrew-polk** [comment]
*[`src/components/Grid/GridColumns.tsx` line 383 at r1](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/572#-OA-f4Z-BNosW6mVo7ny:-OA-hEpJ2xgDyRdaDAmY:b-bsjhxm) ([raw file](https://github.com/BloomBooks/BloomLibrary2/blob/34840a4961799e5c51c2be816956d97b1eaaa870/src/components/Grid/GridColumns.tsx#L383)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I don't see much advantage to the new names.
In fact, if it wasn't for compatibility, I would just make them all match the title as the rest of them do.
</blockquote></details>

I suppose one could argue that it would be a benefit to make them add Reads again so they notice there are both Starts and Finishes. But they would see the new label being Reads Finished now, so that would/could prompt them to go looking anyway.

**Pull request merged**
