### PR TITLE
Add "Export CSV" button to the grid page (BL-9559)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/308)

### CODE REVIEW

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/308)* status: all files reviewed, 7 unresolved discussions (waiting on @StephenMcConnel)

___
*[src/components/Grid/GridControlInternal.tsx, line 162 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/308#-MUnqw-04E62gGAr3GSj:-MUnqw-04E62gGAr3GSk:bjo201n) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/13e51df962451c8d31f47752e13290bbbee48e9d/src/components/Grid/GridControlInternal.tsx#L162)):*
> ```
> descending: s.direction === "asc"
> ```
backwards logic
___
*[src/components/Grid/GridExport.ts, line 3 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/308#-MUnw3Ld6Y1cVG7DOv5Q:-MUnw3Ld6Y1cVG7DOv5R:bqsklyu) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/13e51df962451c8d31f47752e13290bbbee48e9d/src/components/Grid/GridExport.ts#L3)):*
> ```
> import { exportCsv } from "../statistics/exportData";
> ```
Worth moving this to a more common place now?
___
*[src/components/Grid/GridExport.ts, line 21 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/308#-MUnrQspBoEPt7lMjOYm:-MUnrQspBoEPt7lMjOYn:b-b4j3zm) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/13e51df962451c8d31f47752e13290bbbee48e9d/src/components/Grid/GridExport.ts#L21)):*
> ```XML
> }> = [];
> let theCompleteFilter: IFilter;
> let theGridColumnFilters: GridFilter[];
> ```

What advantage do you see for the "the" prefixes?
Is it because you're trying to find a way to distinguish between what would, in pure OO, be class-level members vs local?

I could find very few examples of this pattern (using variables outside functions) in our existing blorg2 code.
One is userInterfaceTagWeAreUsing in Language.ts which happens to have no naming conflict.
Another is static_translationsToCurrentLanguage in GetLocalizations.ts. Perhaps static_ is appropriate here, too, since that is basically how they are functioning?
I might be able to get on board with the "the" prefix, too.
I'm just trying to figure out a consistent naming convention moving forward.
___
*[src/components/Grid/GridExport.ts, line 32 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/308#-MUns-ia-oz74m2EJ1A8:-MUns-ia-oz74m2EJ1A9:b-r4rs2z) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/13e51df962451c8d31f47752e13290bbbee48e9d/src/components/Grid/GridExport.ts#L32)):*
> ```
> setGridExportData
> ```
Would this be better as setGridExportMetadata? Or setGridColumnInfo? Or similar?
I was expecting this to be doing something with the actual data values.
___
*[src/components/Grid/GridExport.ts, line 104 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/308#-MUnyOiUCT3JpnLg0K7O:-MUnyOiUCT3JpnLg0K7P:b-5p9kuu) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/13e51df962451c8d31f47752e13290bbbee48e9d/src/components/Grid/GridExport.ts#L104)):*
> ```XML
>     console.log(`DEBUG: query="${JSON.stringify(query)}"`);
>     console.log(`DEBUG: sortOrder="${sortOrder}"`);
>     const result = await axios.get(`${getConnection().url}classes/books`, {
> ```

I think this was talked about this morning, but it must not have clicked. Please remind me why we can't use the existing code for getting books from parse.
___
*[src/components/Grid/GridPage.tsx, line 14 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/308#-MUnpW7H8axJEYVcFl-M:-MUnpW7I8oEE1OfvkylF:b-sb0qwo) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/13e51df962451c8d31f47752e13290bbbee48e9d/src/components/Grid/GridPage.tsx#L14)):*
> ```
> import DownloadCsvIcon from "../statistics/download-csv.svg";
> ```
Probably worth moving the svg to a common place at this point?
___
*[src/components/statistics/exportData.tsx, line 3 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/308#-MUnplR6C44hH8dd6sS8:-MUnplR6C44hH8dd6sS9:b-umm4f5) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/13e51df962451c8d31f47752e13290bbbee48e9d/src/components/statistics/exportData.tsx#L3)):*
> ```
> import { saveAs } from "file-saver";
> ```
vestigial?

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/308)* status: 2 of 13 files reviewed, 7 unresolved discussions (waiting on @andrew-polk)

___
*[src/components/Grid/GridControlInternal.tsx, line 162 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/308#-MUnqw-04E62gGAr3GSj:-MUo2EMv1wzyltZcWnZW:b-dwx86v) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/13e51df962451c8d31f47752e13290bbbee48e9d/src/components/Grid/GridControlInternal.tsx#L162)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> descending: s.direction === "asc"
> ```
backwards logic
</blockquote></details>

It does seem that way.  but it copied verbatim from about 18 lines below...
___
*[src/components/Grid/GridExport.ts, line 3 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/308#-MUnw3Ld6Y1cVG7DOv5Q:-MUoE8vyEl6FoQaz8FS6:b-ch3uji) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/13e51df962451c8d31f47752e13290bbbee48e9d/src/components/Grid/GridExport.ts#L3)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> import { exportCsv } from "../statistics/exportData";
> ```
Worth moving this to a more common place now?
</blockquote></details>

moved to src/export (../../export relative path)
___
*[src/components/Grid/GridExport.ts, line 21 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/308#-MUnrQspBoEPt7lMjOYm:-MUo3wd50BFsspj8muBD:b9vl4vj) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/13e51df962451c8d31f47752e13290bbbee48e9d/src/components/Grid/GridExport.ts#L21)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

What advantage do you see for the "the" prefixes?
Is it because you're trying to find a way to distinguish between what would, in pure OO, be class-level members vs local?

I could find very few examples of this pattern (using variables outside functions) in our existing blorg2 code.
One is userInterfaceTagWeAreUsing in Language.ts which happens to have no naming conflict.
Another is static_translationsToCurrentLanguage in GetLocalizations.ts. Perhaps static_ is appropriate here, too, since that is basically how they are functioning?
I might be able to get on board with the "the" prefix, too.
I'm just trying to figure out a consistent naming convention moving forward.
</blockquote></details>

static_ would be okay as a prefix.  I didn't have any particular reason for "the" in particular.
___
*[src/components/Grid/GridExport.ts, line 32 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/308#-MUns-ia-oz74m2EJ1A8:-MUo5TlE9WHLb3PdyCv3:b-rgo7zb) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/13e51df962451c8d31f47752e13290bbbee48e9d/src/components/Grid/GridExport.ts#L32)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> setGridExportData
> ```
Would this be better as setGridExportMetadata? Or setGridColumnInfo? Or similar?
I was expecting this to be doing something with the actual data values.
</blockquote></details>

changed function name to setGridExportColumnInfo
___
*[src/components/Grid/GridExport.ts, line 104 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/308#-MUnyOiUCT3JpnLg0K7O:-MUo0sTBD87Y1VnwQlFj:b-7oe979) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/13e51df962451c8d31f47752e13290bbbee48e9d/src/components/Grid/GridExport.ts#L104)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think this was talked about this morning, but it must not have clicked. Please remind me why we can't use the existing code for getting books from parse.
</blockquote></details>

The existing axios call is encoded in a "useAxios" method call.  By the infamous Law of Hooks, we can't use it in response to a button click.  If we made a separate call to useGetBooksForGrid for data from all the books every time inside GridControlInternal, we could reuse the code, but that's an awful lot of overhead that is almost always unneeded.
My compromise was to extract the code for generating the order parameter to an exported function.  The code for generating the query was already an exported function.  I could add the list of keys as an exported variable/function as well, but the axios call itself can't really be reused because of being a hook.
(I'm not sure we talked about this explicitly this morning.)
___
*[src/components/Grid/GridPage.tsx, line 14 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/308#-MUnpW7H8axJEYVcFl-M:-MUoE1VY4nPPObjhw56-:b-ch3uji) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/13e51df962451c8d31f47752e13290bbbee48e9d/src/components/Grid/GridPage.tsx#L14)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> import DownloadCsvIcon from "../statistics/download-csv.svg";
> ```
Probably worth moving the svg to a common place at this point?
</blockquote></details>

moved to src/export (../../export relative path)
___
*[src/components/statistics/exportData.tsx, line 3 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/308#-MUnplR6C44hH8dd6sS8:-MUoEIVbDYw_dzELD9dV:b-t9pica) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/13e51df962451c8d31f47752e13290bbbee48e9d/src/components/statistics/exportData.tsx#L3)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> import { saveAs } from "file-saver";
> ```
vestigial?
</blockquote></details>

Sometimes it compiles without this, sometimes it doesn't.  I haven't figured it out.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/308)* status: all files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

___
*[src/components/Grid/GridControlInternal.tsx, line 162 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/308#-MUnqw-04E62gGAr3GSj:-MUoHHVADeD-lOCKgIm2:b-nnrnjf) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/13e51df962451c8d31f47752e13290bbbee48e9d/src/components/Grid/GridControlInternal.tsx#L162)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

It does seem that way.  but it copied verbatim from about 18 lines below...
</blockquote></details>

I just checked this out. The other is wrong.
We are defaulting to desc sort order (which is wrong, methinks) and displaying it with an up arrow.
So let's go ahead and fix the other. Thanks.
___
*[src/components/Grid/GridExport.ts, line 104 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/308#-MUnyOiUCT3JpnLg0K7O:-MUoIKkD8t_3kPuQIz9d:b-w2q6m8) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/13e51df962451c8d31f47752e13290bbbee48e9d/src/components/Grid/GridExport.ts#L104)):*
> (I'm not sure we talked about this explicitly this morning.)

Yeah, maybe that was something about why we have useGetBooksForGrid in addition to useGetBooks...

I think I would like to see this function in a parse-specific place. LibraryQueryHooks would be the natural place if it wasn't called "hooks".
In LibraryUpdates, there is a similar hookless GET. But I don't want to add another GET to "Updates", either.
So, I think an improvement would be one of these:
1. Add both to LibraryQueryHooks in a separate section stating these aren't hooks but we want to keep parse stuff together.
2. Add a new LibraryQueries (or similar) file which holds both functions.

Also, let's add a comment on this function explaining why we need to have this in addition to the hook version.
I'll leave it to you if you think extracting the keys is worth it.

Thanks
___
*[src/components/statistics/exportData.tsx, line 3 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/308#-MUnplR6C44hH8dd6sS8:-MUoGH7h4Xl4gaVmIDH-:b-xsku6k) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/13e51df962451c8d31f47752e13290bbbee48e9d/src/components/statistics/exportData.tsx#L3)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Sometimes it compiles without this, sometimes it doesn't.  I haven't figured it out.
</blockquote></details>

Hm. I thought you had added it for some other iteration of code but forgot to remove it.
Does seem like it should be here...

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/308)* status: 10 of 16 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[src/components/Grid/GridControlInternal.tsx, line 162 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/308#-MUnqw-04E62gGAr3GSj:-MUobJYL2rYl83tQgWSU:b-896fix) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/13e51df962451c8d31f47752e13290bbbee48e9d/src/components/Grid/GridControlInternal.tsx#L162)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I just checked this out. The other is wrong.
We are defaulting to desc sort order (which is wrong, methinks) and displaying it with an up arrow.
So let's go ahead and fix the other. Thanks.
</blockquote></details>

Done.
___
*[src/components/Grid/GridExport.ts, line 104 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/308#-MUnyOiUCT3JpnLg0K7O:-MUoka7e20MwyNoMokei:b20nr0u) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/13e51df962451c8d31f47752e13290bbbee48e9d/src/components/Grid/GridExport.ts#L104)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> (I'm not sure we talked about this explicitly this morning.)

Yeah, maybe that was something about why we have useGetBooksForGrid in addition to useGetBooks...

I think I would like to see this function in a parse-specific place. LibraryQueryHooks would be the natural place if it wasn't called "hooks".
In LibraryUpdates, there is a similar hookless GET. But I don't want to add another GET to "Updates", either.
So, I think an improvement would be one of these:
1. Add both to LibraryQueryHooks in a separate section stating these aren't hooks but we want to keep parse stuff together.
2. Add a new LibraryQueries (or similar) file which holds both functions.

Also, let's add a comment on this function explaining why we need to have this in addition to the hook version.
I'll leave it to you if you think extracting the keys is worth it.

Thanks
</blockquote></details>

I created a new file src/connection/LibraryQueries.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/308)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
