### PR TITLE
Improvements for transitioning from legacy urls (BL-9426)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/280)

### CODE REVIEW

**Comment by StephenMcConnel** [comment]
We might want to replace error.collectionNotFound with page.collectionNotFound, choosing which wording "we" prefer.

**Review by andrew-polk — COMMENTED** [review]
I've proposed we just use the PageNotFound component everywhere in a comment in the card.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/280#-:-MRX2Zxs1HZ8LzeZIrul:b-axqr3q)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/280)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[src/components/Routes.tsx, line 56 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/280#-MRX52wn3iVWl6N9TH5c:-MRX52wo8Z1ztsvBRx-3:bryzv5z) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/2b4c8c6a3c53b7c9f9c6636a5784626e6670c211/src/components/Routes.tsx#L56)):*
> ```XML
>                 <Route path={"/books"}>
>                     <Redirect to="/" />
>                 </Route>
> ```

While we're messing with this, let's combine the browse and books paths with an array like below. (I'm 99.9% sure making /books "exact" is the right thing to do.)
And let's go ahead and include with and without final slash.

Now that I see how this works better, I think we also need installers to be exact because otherwise, urls like https://bloomlibrary.org/installersAlpha/BloomInstaller.5.0.1238.Alpha.exe won't work.
So let's make download et al be exact with and without trailing slash.

Thanks

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/280)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[src/components/Routes.tsx, line 56 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/280#-MRX52wn3iVWl6N9TH5c:-MR_o1JQ-0QoPgStJcUB:b-b3822e) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/2b4c8c6a3c53b7c9f9c6636a5784626e6670c211/src/components/Routes.tsx#L56)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

While we're messing with this, let's combine the browse and books paths with an array like below. (I'm 99.9% sure making /books "exact" is the right thing to do.)
And let's go ahead and include with and without final slash.

Now that I see how this works better, I think we also need installers to be exact because otherwise, urls like https://bloomlibrary.org/installersAlpha/BloomInstaller.5.0.1238.Alpha.exe won't work.
So let's make download et al be exact with and without trailing slash.

Thanks
</blockquote></details>

Did you decide we don't need the versions with a trailing slash?

**Review by StephenMcConnel — COMMENTED** [review]
oops, I meant error.pageNotFound

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/280#-:-MRX72Qy8aUEn1JcMlg2:b-r4sc54)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/components/Routes.tsx, line 56 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/280#-MRX52wn3iVWl6N9TH5c:-MRX97j29pSeVLpre9RE:b-vmm0o3) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/2b4c8c6a3c53b7c9f9c6636a5784626e6670c211/src/components/Routes.tsx#L56)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

While we're messing with this, let's combine the browse and books paths with an array like below. (I'm 99.9% sure making /books "exact" is the right thing to do.)
And let's go ahead and include with and without final slash.

Now that I see how this works better, I think we also need installers to be exact because otherwise, urls like https://bloomlibrary.org/installersAlpha/BloomInstaller.5.0.1238.Alpha.exe won't work.
So let's make download et al be exact with and without trailing slash.

Thanks
</blockquote></details>

"exact" appears to match either /browse or /browse/.  "strict" is what requires/disallows the trailing slash.

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/280)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
