### PR TITLE
Pass collection instead of filter whenever possible (BL-10900)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/417)

### CODE REVIEW

**Review by JohnThomson — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/417)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/417)* status: 7 of 11 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/components/CollectionInfoWidget.tsx, line 18 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/417#-Mv51A1T4YWDxcVf08TO:-MvKJAeNApdLDVEjNb1Z:b-896fix) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/783fc331021d84fe178cbf68e33653695df251a0/src/components/CollectionInfoWidget.tsx#L18)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

See my comment in the issue. Basically, I suggest removing this widget from BookGroup, and then we should be able to remove the filter prop, make the collection one required, and simplify this widget.
</blockquote></details>

Done.

**Review by JohnThomson — CHANGES_REQUESTED** [review]
Two fairly trivial things, then feel free to merge yourself.

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/417#-:-MvPT8BM32cY-YmAd4jW:btim989)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson and @StephenMcConnel)

___
*[src/components/CollectionInfoWidget.tsx, line 15 at r3](https://reviewable.io/reviews/bloombooks/bloomlibrary2/417#-MvPSqD16imdedjoIh8C:-MvPSqD23NzIFnubdWj7:b-iz55no) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/8789f9afeb6de31f002ec5779484e17e8d9654b8/src/components/CollectionInfoWidget.tsx#L15)):*
> ```XML
> 
> export const CollectionInfoWidget: React.FunctionComponent<{
>     // provide the collection if you have it
> ```

Sorry, this comment is now out of date
___
*[src/components/CollectionInfoWidget.tsx, line 24 at r3](https://reviewable.io/reviews/bloombooks/bloomlibrary2/417#-MvPT0B313_dD09Z-MoF:-MvPT0B313_dD09Z-MoG:b-mgrs1b) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/8789f9afeb6de31f002ec5779484e17e8d9654b8/src/components/CollectionInfoWidget.tsx#L24)):*
> ```XML
>             ? `UrlKey = ${props.collection.urlKey}`
>             : "";
>         const filter = props.collection?.filter
> ```

We can get rid of the ? now this prop is required

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/417)* status: 10 of 11 files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[src/components/CollectionInfoWidget.tsx, line 15 at r3](https://reviewable.io/reviews/bloombooks/bloomlibrary2/417#-MvPSqD16imdedjoIh8C:-MvPXY5Z5lbikbUJezEd:b-896fix) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/8789f9afeb6de31f002ec5779484e17e8d9654b8/src/components/CollectionInfoWidget.tsx#L15)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Sorry, this comment is now out of date
</blockquote></details>

Done.
___
*[src/components/CollectionInfoWidget.tsx, line 24 at r3](https://reviewable.io/reviews/bloombooks/bloomlibrary2/417#-MvPT0B313_dD09Z-MoF:-MvPX_sJ41hW63wIREVs:b-896fix) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/8789f9afeb6de31f002ec5779484e17e8d9654b8/src/components/CollectionInfoWidget.tsx#L24)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

We can get rid of the ? now this prop is required
</blockquote></details>

Done.

**Pull request merged**
