### PR TITLE
Get total books counts for parent collections (BL-10187)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/358)

### CODE REVIEW

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/358)* status: all files reviewed, 3 unresolved discussions (waiting on @StephenMcConnel)

___
*[src/components/CollectionPage.tsx, line 69 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/358#-Mh-jzf87rzyhilwUMI4:-Mh-jzf87rzyhilwUMI5:b-1uk9re) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/d657cf75f866179a248cd7b28cb61fb2bda10657/src/components/CollectionPage.tsx#L69)):*
> ```XML
>             setCountString("");
>         }
>     }
> ```

Did you look into trying to push this into the BookCount component?
I guess we have to answer: is there any case in which we don't want to include child collections in the book count of a collection?
I can't think of one...
___
*[src/components/CollectionPage.tsx, line 197 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/358#-Mh-c0JZ6t2kCgy88ITv:-Mh-c0JZ6t2kCgy88ITw:b-h9kqiu) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/d657cf75f866179a248cd7b28cb61fb2bda10657/src/components/CollectionPage.tsx#L197)):*
> ```
> getCollectionFilter
> ```
I'm struggling a bit with the name.
How about something like `getFilterForCollectionAndChildren`?
Similarly, `collectCollectionFilters`might become something like `collectCollectionAndChildrenFilter`.
Or `gather..` or `accumulate...` to avoid double use of `collect`.

Similarly for `collectionFilter` and `setCollectionFilter`.
___
*[src/components/CollectionPage.tsx, line 208 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/358#-Mh-kkC83sLRgqpSurt1:-Mh-kkC83sLRgqpSurt2:bl2or8f) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/d657cf75f866179a248cd7b28cb61fb2bda10657/src/components/CollectionPage.tsx#L208)):*
> ```XML
> // Accumulate the filters for this collection and recursively all of
> // its child collections into the supplied IFilter[] array.
> function collectCollectionFilters(
> ```

Do these two new functions want to live somewhere else? `Collections.tsx`?

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/358)* status: all files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[src/components/CollectionPage.tsx, line 69 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/358#-Mh-jzf87rzyhilwUMI4:-Mh0qZWwAnta0SsTVXsK:bvuik4f) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/d657cf75f866179a248cd7b28cb61fb2bda10657/src/components/CollectionPage.tsx#L69)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Did you look into trying to push this into the BookCount component?
I guess we have to answer: is there any case in which we don't want to include child collections in the book count of a collection?
I can't think of one...
</blockquote></details>

Done.  or at least moved to where BookCount is invoked by StandardBannerLayout.
___
*[src/components/CollectionPage.tsx, line 197 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/358#-Mh-c0JZ6t2kCgy88ITv:-Mh0l6kp8XRFRm-xjc6O:b-pgm72c) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/d657cf75f866179a248cd7b28cb61fb2bda10657/src/components/CollectionPage.tsx#L197)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> getCollectionFilter
> ```
I'm struggling a bit with the name.
How about something like `getFilterForCollectionAndChildren`?
Similarly, `collectCollectionFilters`might become something like `collectCollectionAndChildrenFilter`.
Or `gather..` or `accumulate...` to avoid double use of `collect`.

Similarly for `collectionFilter` and `setCollectionFilter`.
</blockquote></details>

Done.  changed to getFilterForCollectionAndChildren and gatherCollectionAndChildrenFilters
___
*[src/components/CollectionPage.tsx, line 208 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/358#-Mh-kkC83sLRgqpSurt1:-Mh0l3Qr7EZ9fs1XWCf9:butgb33) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/d657cf75f866179a248cd7b28cb61fb2bda10657/src/components/CollectionPage.tsx#L208)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Do these two new functions want to live somewhere else? `Collections.tsx`?
</blockquote></details>

Done.  moved to Collections.tsx.

**Review by andrew-polk — COMMENTED** [review]
Looks good so far, but I think you're planning to try to enhance the GET to a POST with body to work around the url getting too long.
If you're doing that as a separate change, this can be merged.

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/358#-:-Mh0zA_s4TI0cKxKZUIa:bkik8f1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/358)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
