### PR TITLE
Add row to ByLanguage for SL books in unknown sign language (BL-9300)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/235)

### CODE REVIEW

**Review by JohnThomson — COMMENTED** [review]
The diff is a bit difficult to follow here. What's going on is:
- the double loop over languages and books is turned inside out to become a loop over books outside a loop over languages
- this allows us to detect that a particular book has no feature:lang tag for the relevant feature
- the code for adding a book to a language list is extracted into a local function so we can use it twice
- books with no feature:lang tag are added to a special list with a fake language

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/235#-:-MO1n71i-YbeZn3c1uEU:b-c7oil4)* status: 0 of 2 files reviewed, all discussions resolved

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/235)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/components/ByLanguageGroups.tsx, line 98 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/235#-MO1qohm-MLT_AHggyPL:-MO1qohm-MLT_AHggyPM:b3ra7mm) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/4f44c5687c295a38ec828a15b033bdae20e4f7f7/src/components/ByLanguageGroups.tsx#L98)):*
> ```XML
>                 if (
>                     !foundOneLanguage &&
>                     props.filter.feature === "signLanguage"
> ```

I couldn't convince myself based on the code that this should be specific to the sign language feature. And indeed when I tried your code and commented this line, I see several other features which then get an "Unknown" row.
Shouldn't we make this generic for all features?

So that would mean removing this line, changing the "isoCode" to "unknown" or similar, and modifying the description in the l10n json file.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/235)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/components/ByLanguageGroups.tsx, line 98 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/235#-MO1qohm-MLT_AHggyPL:-MO2MDEs4FLUlM__ng_J:b-896fix) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/4f44c5687c295a38ec828a15b033bdae20e4f7f7/src/components/ByLanguageGroups.tsx#L98)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I couldn't convince myself based on the code that this should be specific to the sign language feature. And indeed when I tried your code and commented this line, I see several other features which then get an "Unknown" row.
Shouldn't we make this generic for all features?

So that would mean removing this line, changing the "isoCode" to "unknown" or similar, and modifying the description in the l10n json file.
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/235)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/235)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/235)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
