### PR TITLE
BL-9602 Add Stats to Grid

### PR DESCRIPTION
**Pull request by gmartin7**
* reads
* downloads

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/307)

### CODE REVIEW

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/307)* status: 0 of 3 files reviewed, 1 unresolved discussion

___
*[src/components/Grid/GridColumns.tsx, line 256 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/307#-MUiv3q25JT2aiRAzLQS:-MUiv3q25JT2aiRAzLQT:bdtdu5w) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/5648871470585b05025d4ae3ccaa3b3831638c1b/src/components/Grid/GridColumns.tsx#L256)):*
> ```XML
>             getCellValue: (b: Book) => (
>                 <GridBookDownloads key={b.id} book={b} />
>             ),
> ```

The extra parentheses on this one are just Prettier's interpretation of what's needed. They make no difference.

**Review by hatton — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/307)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @gmartin7)

___
*[src/components/Grid/GridColumns.tsx, line 249 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/307#-MUiwFC32x1Eg1EkossG:-MUiwFC32x1Eg1EkossH:b-jdcfsr) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/5648871470585b05025d4ae3ccaa3b3831638c1b/src/components/Grid/GridColumns.tsx#L249)):*
> ```XML
>             name: "reads",
>             sortingEnabled: true,
>             getCellValue: (b: Book) => <GridBookReads key={b.id} book={b} />,
> ```

What is special about this simple number that it requires its own component, vs. just a string?
___
*[src/components/Grid/GridColumns.tsx, line 255 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/307#-MUiw4pO2Hxc_C_K3Czf:-MUiw4pP-7je1ypscnc0:b-jdcfsr) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/5648871470585b05025d4ae3ccaa3b3831638c1b/src/components/Grid/GridColumns.tsx#L255)):*
> ```XML
>             sortingEnabled: true,
>             getCellValue: (b: Book) => (
>                 <GridBookDownloads key={b.id} book={b} />
> ```

What is special about this simple number that it requires its own component, vs. just a string?

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/307)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @gmartin7 and @hatton)

___
*[src/components/Grid/GridColumns.tsx, line 249 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/307#-MUiwFC32x1Eg1EkossG:-MUiwPVX6an2sYEvarKg:b-cljiy1) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/5648871470585b05025d4ae3ccaa3b3831638c1b/src/components/Grid/GridColumns.tsx#L249)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

What is special about this simple number that it requires its own component, vs. just a string?
</blockquote></details>

This simple number comes from a separate parse db query of statistics for the book. The book object that we are fed doesn't have that information. (Same below.)

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/307)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @hatton)

___
*[src/components/Grid/GridColumns.tsx, line 255 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/307#-MUiw4pO2Hxc_C_K3Czf:-MUiwu0f956a57mYdR6m:byr4ffv) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/5648871470585b05025d4ae3ccaa3b3831638c1b/src/components/Grid/GridColumns.tsx#L255)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

What is special about this simple number that it requires its own component, vs. just a string?
</blockquote></details>

see above

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/307)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @gmartin7 and @hatton)

___
*[src/components/Grid/GridColumns.tsx, line 249 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/307#-MUiwFC32x1Eg1EkossG:-MUix1KH14VLZGgAt8fV:bjzr1j7) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/5648871470585b05025d4ae3ccaa3b3831638c1b/src/components/Grid/GridColumns.tsx#L249)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

This simple number comes from a separate parse db query of statistics for the book. The book object that we are fed doesn't have that information. (Same below.)
</blockquote></details>

Thx. I'm wondering what the implications are this for what Steve is doing (which is why we are adding these columns). If it's not just a string, can even export it?

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/307)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[src/components/Grid/GridColumns.tsx, line 249 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/307#-MUiwFC32x1Eg1EkossG:-MUiy4MPB0eNCJHDOag6:bzatk8o) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/5648871470585b05025d4ae3ccaa3b3831638c1b/src/components/Grid/GridColumns.tsx#L249)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Thx. I'm wondering what the implications are this for what Steve is doing (which is why we are adding these columns). If it's not just a string, can even export it?
</blockquote></details>

Do you know that answer to John's question, @johnthomson ? I have no idea.

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/307)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[src/components/Grid/GridColumns.tsx, line 249 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/307#-MUiwFC32x1Eg1EkossG:-MUizTApEoYrO6q98bRg:b-8raqbi) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/5648871470585b05025d4ae3ccaa3b3831638c1b/src/components/Grid/GridColumns.tsx#L249)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Do you know that answer to John's question, @johnthomson ? I have no idea.
</blockquote></details>

This should be a q for Steve, not JT.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/307)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[src/components/Grid/GridColumns.tsx, line 249 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/307#-MUiwFC32x1Eg1EkossG:-MUj-I2Y-KpiICdYlpT1:blstntq) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/5648871470585b05025d4ae3ccaa3b3831638c1b/src/components/Grid/GridColumns.tsx#L249)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

This should be a q for Steve, not JT.
</blockquote></details>

I think acquiring the data for export will be the tricky part, not formatting it.  But I think that should be doable with a Promise.all() incorporating the two queries over the entire database.

**Comment by gmartin7** [comment]
Out-of-date. Steve did this in another PR.

**Pull request closed without merging**
