### PR TITLE
BL-9381 About Box work

### PR DESCRIPTION
**Pull request by hatton**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/283)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 19 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/283)* status: all files reviewed, 8 unresolved discussions (waiting on @hatton)

___
*[src/components/markdown/Section.tsx, line 19 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/283#-MRa8iUw-cRZCTfY13I0:-MRa8iUw-cRZCTfY13I1:b-8s4wcv) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/0f3bae89924a2eefc9be338ca5548c94fdc0c00d/src/components/markdown/Section.tsx#L19)):*
> ```XML
>     className?: string;
>     prose?: boolean;
> }
> ```

Since in css, `color` means text color, it would probably confuse our future selves much less for background color to be something like `backgroundColor`.
___
*[src/components/markdown/Vimeo.tsx, line 3 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/283#-MRa7M758MBkZAUGgizg:-MRa7M758MBkZAUGgizh:b-y96ph4) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/0f3bae89924a2eefc9be338ca5548c94fdc0c00d/src/components/markdown/Vimeo.tsx#L3)):*
> ```XML
> // Display a block with a colored background.
> // Optional padding is provided.
> // Optional background image is allowed. (This feature is very rudimentary and untested at present.)
> ```

I think these comments are left from some copy/paste?
___
*[src/components/markdown/Vimeo.tsx, line 21 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/283#-MRa7k2C8tr4qDuqCLtw:-MRa7k2C8tr4qDuqCLtx:b-j1oxhi) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/0f3bae89924a2eefc9be338ca5548c94fdc0c00d/src/components/markdown/Vimeo.tsx#L21)):*
> ```
> padding: 56.25% 0 0 0;
> ```
This seems like it is probably over-specific to this context?
___
*[src/components/markdown/Vimeo.tsx, line 28 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/283#-MRa7agy5qauiCuNm5el:-MRa7agy5qauiCuNm5em:b-4ves7q) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/0f3bae89924a2eefc9be338ca5548c94fdc0c00d/src/components/markdown/Vimeo.tsx#L28)):*
> ```
> "https://player.vimeo.com/video/141561934?title=0&byline=0&portrait=0&autoplay=1"
> ```
Shouldn't this get passed in somehow?
___
*[src/components/markdown/Vimeo.tsx, line 40 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/283#-MRa7q4M3VY4OnCN40j7:-MRa7q4M3VY4OnCN40j8:b-by3t8s) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/0f3bae89924a2eefc9be338ca5548c94fdc0c00d/src/components/markdown/Vimeo.tsx#L40)):*
> ```
> title={"z"}
> ```
Seems like we should remove this or set it correctly.
___
*[src/components/markdown/BlorgMarkdown.tsx, line 43 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/283#-MRa6LBQ5yWymSSHZZ6v:-MRa6LBQ5yWymSSHZZ6w:bli6s57) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/0f3bae89924a2eefc9be338ca5548c94fdc0c00d/src/components/markdown/BlorgMarkdown.tsx#L43)):*
> ```XML
>             // NB: we need this to be lower case because, when using an html
>             // formatter to work on a long markdown document, <Section> will get
>             // changed to <section>
> ```

Looks like this comment is obsolete?
___
*[src/components/markdown/BlorgMarkdown.tsx, line 70 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/283#-MRa6NLl2Vp8lb73RCzJ:-MRa6NLl2Vp8lb73RCzK:bf7u1mw) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/0f3bae89924a2eefc9be338ca5548c94fdc0c00d/src/components/markdown/BlorgMarkdown.tsx#L70)):*
> ```XML
>             //         margin-right: auto;
>             //     }
>             // `}
> ```

Any reason to keep this?
___
*[src/components/markdown/WindowsInstallerDownload.tsx, line 48 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/283#-MRa7z0R-qapTmgdjOkN:-MRa7z0R-qapTmgdjOkO:b-57t7jt) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/0f3bae89924a2eefc9be338ca5548c94fdc0c00d/src/components/markdown/WindowsInstallerDownload.tsx#L48)):*
> ```XML
>                         `}
>                     >
>                         Download
> ```

This and below got regressed due to a bad merge.
They should be FormattedMessage components.

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/283)* status: all files reviewed, 8 unresolved discussions (waiting on @andrew-polk)

___
*[src/components/markdown/Section.tsx, line 19 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/283#-MRa8iUw-cRZCTfY13I0:-MRahJDBEVLH2VRqeoRM:b-896fix) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/0f3bae89924a2eefc9be338ca5548c94fdc0c00d/src/components/markdown/Section.tsx#L19)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Since in css, `color` means text color, it would probably confuse our future selves much less for background color to be something like `backgroundColor`.
</blockquote></details>

Done.
___
*[src/components/markdown/Vimeo.tsx, line 3 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/283#-MRa7M758MBkZAUGgizg:-MRahPpiAMVmaD43faiq:b-896fix) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/0f3bae89924a2eefc9be338ca5548c94fdc0c00d/src/components/markdown/Vimeo.tsx#L3)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think these comments are left from some copy/paste?
</blockquote></details>

Done.
___
*[src/components/markdown/Vimeo.tsx, line 21 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/283#-MRa7k2C8tr4qDuqCLtw:-MRahVnM9yaWDpp4pYgD:bf17fyi) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/0f3bae89924a2eefc9be338ca5548c94fdc0c00d/src/components/markdown/Vimeo.tsx#L21)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> padding: 56.25% 0 0 0;
> ```
This seems like it is probably over-specific to this context?
</blockquote></details>

I don't know. That's from Steve's work.
___
*[src/components/markdown/Vimeo.tsx, line 28 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/283#-MRa7agy5qauiCuNm5el:-MRahbQR89gPoZTydq72:b-7lj87b) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/0f3bae89924a2eefc9be338ca5548c94fdc0c00d/src/components/markdown/Vimeo.tsx#L28)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> "https://player.vimeo.com/video/141561934?title=0&byline=0&portrait=0&autoplay=1"
> ```
Shouldn't this get passed in somehow?
</blockquote></details>

oops!
___
*[src/components/markdown/Vimeo.tsx, line 40 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/283#-MRa7q4M3VY4OnCN40j7:-MRahjhj4PnydgtDbWZp:b-896fix) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/0f3bae89924a2eefc9be338ca5548c94fdc0c00d/src/components/markdown/Vimeo.tsx#L40)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> title={"z"}
> ```
Seems like we should remove this or set it correctly.
</blockquote></details>

Done.
___
*[src/components/markdown/BlorgMarkdown.tsx, line 43 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/283#-MRa6LBQ5yWymSSHZZ6v:-MRagh2qDMO0aPAKTKz6:b-25pxuc) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/0f3bae89924a2eefc9be338ca5548c94fdc0c00d/src/components/markdown/BlorgMarkdown.tsx#L43)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Looks like this comment is obsolete?
</blockquote></details>

It is still true, but it turns out that html formatter is dangerous to markdown. Removed.
___
*[src/components/markdown/BlorgMarkdown.tsx, line 70 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/283#-MRa6NLl2Vp8lb73RCzJ:-MRaguFe5k5VxFra11OL:b-896fix) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/0f3bae89924a2eefc9be338ca5548c94fdc0c00d/src/components/markdown/BlorgMarkdown.tsx#L70)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Any reason to keep this?
</blockquote></details>

Done.
___
*[src/components/markdown/WindowsInstallerDownload.tsx, line 48 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/283#-MRa7z0R-qapTmgdjOkN:-MRai7qZ0k2B1kFXbut2:b-896fix) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/0f3bae89924a2eefc9be338ca5548c94fdc0c00d/src/components/markdown/WindowsInstallerDownload.tsx#L48)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This and below got regressed due to a bad merge.
They should be FormattedMessage components.
</blockquote></details>

Done.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/283)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[src/components/markdown/Vimeo.tsx, line 21 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/283#-MRa7k2C8tr4qDuqCLtw:-MRe_r9p1o7NQdwn9tYd:b-p5cb4c) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/0f3bae89924a2eefc9be338ca5548c94fdc0c00d/src/components/markdown/Vimeo.tsx#L21)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I don't know. That's from Steve's work.
</blockquote></details>

Odd. I can't find that in the current code anywhere.
But if you think it is ok, that is the only outstanding question I have, so go ahead and merge.

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/283)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/components/markdown/Vimeo.tsx, line 21 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/283#-MRa7k2C8tr4qDuqCLtw:-MRedowT3hNfZgne3Vfb:bp0dqz4) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/0f3bae89924a2eefc9be338ca5548c94fdc0c00d/src/components/markdown/Vimeo.tsx#L21)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Odd. I can't find that in the current code anywhere.
But if you think it is ok, that is the only outstanding question I have, so go ahead and merge.
</blockquote></details>

Sorry, I was wrong. This came from vimeo's instructions.

**Pull request merged**
