### PR TITLE
Clean up unused packages

### PR DESCRIPTION
**Pull request by andrew-polk**
Mostly discovered by running and verifying `depchecks`

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/259)

### CODE REVIEW

**Review by gmartin7 — COMMENTED** [review]
> Reviewed 5 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/259)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[package.json, line 45 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/259#-MQn_2rwBvrZBXFbUFg5:-MQn_2rxAdyHkTRlRk0I:b8mlc6w) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/9ff0f8068997886ff7a415e6b39ad8dc778a8aba/package.json#L45)):*
> ```JSON
>         "@types/react-router-dom": "^5.1.5",
>         "@types/swiper": "^5.4.1",
>         "@types/voca": "^1.4.0",
> ```

These types are deleted, but no corresponding package deleted? Is it already deleted?

**Review by gmartin7 — APPROVED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/259)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/259)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[package.json, line 45 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/259#-MQn_2rwBvrZBXFbUFg5:-MQnaPfu7JrdYSHsY54f:b-z2ssvu) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/9ff0f8068997886ff7a415e6b39ad8dc778a8aba/package.json#L45)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

These types are deleted, but no corresponding package deleted? Is it already deleted?
</blockquote></details>

Not sure if it was ever there or what. Certainly not used now.

**Review by gmartin7 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/259)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @andrew-polk)

**Pull request merged**
