### PR TITLE
Feature Matrix Page

### PR DESCRIPTION
**Pull request by hatton**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/196)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/196)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[src/index.css, line 41 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/196#-MLT6sXe9WidIA9DNw2t:-MLT6sXe9WidIA9DNw2u:b7dzeth) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/e0fcbb6dc181c19d63a26cafcf5bc5cf9a9061c6/src/index.css#L41)):*
## This was also applying to breadcrumbs:

---

## and the stats description (probably ok):


### vs

---
## Also, while taking this out, we can remove the rule below:
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> .base-contentful-page ul {
>    /* revert the rules set above for all ul */
>    list-style: revert;
>    padding: revert;
>}
> ```
</details>

___
*[src/components/ContentfulMarkdownPart.tsx, line 40 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/196#-MLT7Ypw5jeI-Pj_BRgE:-MLT7Ypw5jeI-Pj_BRgF:blnn6j7) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/18995db2c22e272c9e6ce5ca89b853384fac1fe7/src/components/ContentfulMarkdownPart.tsx#L40)):*
> ```XML
>                 },
>                 Feature: Feature,
>                 FeatureGroup: FeatureGroup,
> ```

More curiosity than anything, but if we don't need the `component: ` part for these last two, do we need it for the others? Maybe it is different because those are nested inside other ones?

**Review by hatton — COMMENTED** [review]
Also introduced MUI `Container` to center things and removed remaining styles from ContentfulMarkdownPart. This will break Gordon's about stuff but that stuff belongs in something specific to the fancy about page, rather than this class.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/196#-:-MLUCD5S4_IMwJjKtDyZ:b-uk5tqt)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/index.css, line 41 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/196#-MLT6sXe9WidIA9DNw2t:-MLUC-T449dRzPCTiF-a:b-xw7434) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/e0fcbb6dc181c19d63a26cafcf5bc5cf9a9061c6/src/index.css#L41)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

## This was also applying to breadcrumbs:

---

## and the stats description (probably ok):


### vs

---
## Also, while taking this out, we can remove the rule below:
> ```
> .base-contentful-page ul {
>    /* revert the rules set above for all ul */
>    list-style: revert;
>    padding: revert;
>}
> ```
</blockquote></details>

I fixed breadcrumbs, left the bullets in /stats

**Review by gmartin7 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/196)* status: 2 of 7 files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[src/components/pages/ContentfulPage.tsx, line 29 at r2](https://reviewable.io/reviews/bloombooks/bloomlibrary2/196#-MLUEMUE72giPjj3Lj5a:-MLUEMUF1AoPS-zSjpy7:b-ag006x) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/ed81cb078e5d224c84212c3cde8936a3205747fa/src/components/pages/ContentfulPage.tsx#L29)):*
> ```XML
> 
>     return (
>         <Container maxWidth="md">
> ```

Where does "md" come from?

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/196)* status: 2 of 7 files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @gmartin7)

___
*[src/components/pages/ContentfulPage.tsx, line 29 at r2](https://reviewable.io/reviews/bloombooks/bloomlibrary2/196#-MLUEMUE72giPjj3Lj5a:-MLUEeqKBFNRxY6TsvAs:b-fxvswh) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/ed81cb078e5d224c84212c3cde8936a3205747fa/src/components/pages/ContentfulPage.tsx#L29)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Where does "md" come from?
</blockquote></details>

their api

**Review by gmartin7 — COMMENTED** [review]
Right. I meant to move that to `index.css`. Oops.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/196#-:-MLUKnABCYPLxgvOHoli:bg69z7r)* status: 2 of 7 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/196)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
