### PR TITLE
Allow subcollections to use layouts (BL-10722)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/387)

### CODE REVIEW

**Review by JohnThomson — CHANGES_REQUESTED** [review]
Looks good with one puzzle noted below

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/387#-:-Mqpi4BQ8-FR5fkO6EFy:b-msdpct)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/components/CollectionLayout.tsx, line 31 at r2](https://reviewable.io/reviews/bloombooks/bloomlibrary2/387#-Mqpgwss3G0DAAQNEFW1:-Mqpgwss3G0DAAQNEFW2:bf1dqrk) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/5287e0bf980427d0d6b84f950e3a4bb1d0957543/src/components/CollectionLayout.tsx#L31)):*
> ```XML
>     if (props.collection.filter) {
>         if (props.defaultLayoutOverride && !props.collection.rawLayout)
>             return props.defaultLayoutOverride;
> ```

I expected props.defaultLayoutOverride to be used in place of props.collection.layout in this case (since the latter is going to be 'by-topic' by default)...but you are returning it as the whole thing to display for the component where every other case ends up returning a collection of book cards. If this isn't a mistake, I think it needs explanation.

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/387)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/components/CollectionLayout.tsx, line 31 at r2](https://reviewable.io/reviews/bloombooks/bloomlibrary2/387#-Mqpgwss3G0DAAQNEFW1:-MqpwQ9uESe6dZPZhq9f:bk9mkgy) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/5287e0bf980427d0d6b84f950e3a4bb1d0957543/src/components/CollectionLayout.tsx#L31)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I expected props.defaultLayoutOverride to be used in place of props.collection.layout in this case (since the latter is going to be 'by-topic' by default)...but you are returning it as the whole thing to display for the component where every other case ends up returning a collection of book cards. If this isn't a mistake, I think it needs explanation.
</blockquote></details>

I realized that, for now, it isn't worth complicating CollectionLayout at all. See what you think.

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/387)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[src/components/CollectionLayout.tsx, line 20 at r3](https://reviewable.io/reviews/bloombooks/bloomlibrary2/387#-Mqtr4Zo2yisNGwMX9aS:-Mqtr4Zo2yisNGwMX9aT:b-yqhc3e) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/da5751e9584f7eb37c7014f784c7db2df6695174/src/components/CollectionLayout.tsx#L20)):*
> ```XML
>         switch (props.collection.layout) {
>             default:
>                 <ByTopicsGroups collection={props.collection} />;
> ```

(a) doesn't this need to be either returned or assigned to booksComponent?
(b) why not just combine default: and case: "by-topic" to select the same code path?

**Review by JohnThomson — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/387)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/387)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/components/CollectionLayout.tsx, line 31 at r2](https://reviewable.io/reviews/bloombooks/bloomlibrary2/387#-Mqpgwss3G0DAAQNEFW1:-MqtrgRk31peCiFzCtaZ:b-pdve9u) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/5287e0bf980427d0d6b84f950e3a4bb1d0957543/src/components/CollectionLayout.tsx#L31)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I realized that, for now, it isn't worth complicating CollectionLayout at all. See what you think.
</blockquote></details>

Yes, I think it is clearer

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/387)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/components/CollectionLayout.tsx, line 20 at r3](https://reviewable.io/reviews/bloombooks/bloomlibrary2/387#-Mqtr4Zo2yisNGwMX9aS:-MqtwW2NEUKyDj3F8XvR:brkuuvc) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/da5751e9584f7eb37c7014f784c7db2df6695174/src/components/CollectionLayout.tsx#L20)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

(a) doesn't this need to be either returned or assigned to booksComponent?
(b) why not just combine default: and case: "by-topic" to select the same code path?
</blockquote></details>

Good catch. Not sure how I lost that assignment. But also those cases should be combined, yes.

**Review by JohnThomson — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/387#-:-MqtycVLAO6yq1r9_yvU:bnfp4nl)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @JohnThomson)

**Review by JohnThomson — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/387)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @andrew-polk)

**Pull request merged**
