### PR TITLE
BL-9259 Remove Mui Link, only use BlorgLink

### PR DESCRIPTION
**Pull request by gmartin7**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/226)

### CODE REVIEW

**Review by JohnThomson — CHANGES_REQUESTED** [review]
Looks good, with two minor points to consider.

> Reviewed 19 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/226#-:-MNZVZ3i2QvL_wJKzrEH:b-ho9u8a)* status: all files reviewed, 2 unresolved discussions (waiting on @gmartin7)

___
*[src/components/BookDetail/BookDetail.tsx, line 203 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/226#-MNZUTl-BHmKEZ9f73N7:-MNZUTl-BHmKEZ9f73N8:bfbuoly) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/cec7798908cbd685a611d22803cb896194bf7cf6/src/components/BookDetail/BookDetail.tsx#L203)):*
> ```XML
>                         so you can translate the book. A such only needed where the Translate button
>                         is missing, e.g., mobile and Mac. But we haven't created the page it should link
>                         to yet, so we're not showing it anywhere. And if we ever do, switch to BlorgLink!
> ```

Looks like you already have?
___
*[src/components/Grid/GridColumns.tsx, line 57 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/226#-MNZVI6d0bs0pYwlN9QS:-MNZVI6d0bs0pYwlN9QT:burq7e4) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/5a95f15daac7d5ddc65325c34a8821a9498ac29e/src/components/Grid/GridColumns.tsx#L57)):*
> ```XML
>                             : "grey !important"};
>                     `}
>                     target="_blank"
> ```

I'm not clear why this was deleted. Presumably at some point we wanted opening a book from the grid to use a new tab...is that no longer wanted?

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/226)* status: 17 of 19 files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[src/components/BookDetail/BookDetail.tsx, line 203 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/226#-MNZUTl-BHmKEZ9f73N7:-MNZapP64rX5QtOZnDbW:b-896fix) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/cec7798908cbd685a611d22803cb896194bf7cf6/src/components/BookDetail/BookDetail.tsx#L203)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Looks like you already have?
</blockquote></details>

Done.
___
*[src/components/Grid/GridColumns.tsx, line 57 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/226#-MNZVI6d0bs0pYwlN9QS:-MNZa98S1CHYQ0X9PXx7:bhgkqgc) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/5a95f15daac7d5ddc65325c34a8821a9498ac29e/src/components/Grid/GridColumns.tsx#L57)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I'm not clear why this was deleted. Presumably at some point we wanted opening a book from the grid to use a new tab...is that no longer wanted?
</blockquote></details>

Good catch! In general, BlorgLink now automatically provides the `target` attribute in cases where it was needed (embedded in an iframe or an external link), but this was the one case where we actually wanted an internal `BL` link to open a new tab! Fixed.

**Review by JohnThomson — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/226)* status: 17 of 19 files reviewed, all discussions resolved (waiting on @JohnThomson)

**Review by JohnThomson — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/226)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Pull request merged**
