### PR TITLE
Add ColoredBlock component to support new About Bloom page (BL-9381)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/255)

### CODE REVIEW

**Review by hatton — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/255)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[src/components/ColoredBlock.tsx, line 22 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/255#-MQYxcbn2Ecg0hCLNOcS:-MQYxcbn2Ecg0hCLNOcT:b8kx1nq) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/aa0b85a4bb6cc5aa857d042dfed5fdf2fcbcb602/src/components/ColoredBlock.tsx#L22)):*
> ```XML
>     };
>     return (
>         <React.Fragment>
> ```

The Fragment doesn't do anything here, since you already only have one child.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/255)* status: all files reviewed, 3 unresolved discussions (waiting on @StephenMcConnel)

___
*[src/components/ColoredBlock.tsx, line 8 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/255#-MQYzBOy55Z9r5ixOF9k:-MQYzBOy55Z9r5ixOF9l:bfduqj8) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/aa0b85a4bb6cc5aa857d042dfed5fdf2fcbcb602/src/components/ColoredBlock.tsx#L8)):*
> ```XML
> export interface IColoredBlockProps extends React.HTMLAttributes<HTMLElement> {
>     color: string; // could be color name or RGB value like "#b1e29d"
>     padding?: string; // optional measurement like "30px"
> ```

Should this be something like rightLeftPadding? 
Otherwise, I think it would be better to do padding: props.padding below and the caller will be responsible for providing 0 top and bottom. (e.g. padding="0px 30px")
___
*[src/components/ColoredBlock.tsx, line 15 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/255#-MQYz92X9JmkTghIWMQ2:-MQYz92X9JmkTghIWMQ3:bueq00l) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/aa0b85a4bb6cc5aa857d042dfed5fdf2fcbcb602/src/components/ColoredBlock.tsx#L15)):*
> ```
> let
> ```
const

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/255)* status: all files reviewed, 3 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[src/components/ColoredBlock.tsx, line 8 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/255#-MQYzBOy55Z9r5ixOF9k:-MQZ6k88-zZhQSMvA0d1:b-mrt3hw) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/aa0b85a4bb6cc5aa857d042dfed5fdf2fcbcb602/src/components/ColoredBlock.tsx#L8)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Should this be something like rightLeftPadding? 
Otherwise, I think it would be better to do padding: props.padding below and the caller will be responsible for providing 0 top and bottom. (e.g. padding="0px 30px")
</blockquote></details>

Done.  changed to just set padding.  (most flexible)
___
*[src/components/ColoredBlock.tsx, line 15 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/255#-MQYz92X9JmkTghIWMQ2:-MQZ6ofQ8dOsk51dtDgw:b-896fix) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/aa0b85a4bb6cc5aa857d042dfed5fdf2fcbcb602/src/components/ColoredBlock.tsx#L15)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> let
> ```
const
</blockquote></details>

Done.
___
*[src/components/ColoredBlock.tsx, line 22 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/255#-MQYxcbn2Ecg0hCLNOcS:-MQZ6pkxBgA4GJhTvCQp:b-896fix) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/aa0b85a4bb6cc5aa857d042dfed5fdf2fcbcb602/src/components/ColoredBlock.tsx#L22)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

The Fragment doesn't do anything here, since you already only have one child.
</blockquote></details>

Done.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/255)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

**Review by andrew-polk — APPROVED** [review]
> Dismissed @hatton from a discussion.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/255)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
