### PR TITLE
Add attribution for ip2location. (BL-10736)

### PR DESCRIPTION
**Pull request by sujeffreyl**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/409)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/409)* status: all files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

___
*[src/components/statistics/StatsCredits.tsx, line 18 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/409#-MuDEPXg57RhqOZ67NjG:-MuDEPXg57RhqOZ67NjH:b-bghdox) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/ea9c67558ed6416f27babeebdb65db302417e56a/src/components/statistics/StatsCredits.tsx#L18)):*
> ```XML
>                 `}
>             >
>                 Credits
> ```

This is tricky... while I would hate to ask our localizers to translate the sentence below...
We should probably internationalize "Credits".
Let's let JH weigh in on the UI first.

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/409)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/components/statistics/StatsCredits.tsx, line 18 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/409#-MuDEPXg57RhqOZ67NjG:-MuDEufv1G-RPJYcJUaA:b-1wlltl) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/ea9c67558ed6416f27babeebdb65db302417e56a/src/components/statistics/StatsCredits.tsx#L18)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This is tricky... while I would hate to ask our localizers to translate the sentence below...
We should probably internationalize "Credits".
Let's let JH weigh in on the UI first.
</blockquote></details>

Let's 
* drop "Credits",
* don't localize anything related to this
* drop "or product"

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/409)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/components/statistics/StatsCredits.tsx, line 18 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/409#-MuDEPXg57RhqOZ67NjG:-MuDHZ5d30-CGWSI2UXM:bjyhda4) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/ea9c67558ed6416f27babeebdb65db302417e56a/src/components/statistics/StatsCredits.tsx#L18)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Let's 
* drop "Credits",
* don't localize anything related to this
* drop "or product"
</blockquote></details>

Sure thing, thanks!

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/409)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sujeffreyl)

**Pull request merged**
