### PR TITLE
Easier subcollection embedding, Phase 1 (BL-9720)

### PR DESCRIPTION
**Pull request by sujeffreyl**
Based on passing in bl-domain and checking DomainEmbeddingSettings in contentful

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/319)

### CODE REVIEW

**Review by hatton — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/319)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @sujeffreyl)

___
*[public/embed-bloomlibrary.js, line 64 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/319#-MW_yMpQ8gP80Z0dBaNC:-MW_yMpQ8gP80Z0dBaND:b-l3bv12) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/d9b799983eed8509eab93628679c1a83ddd2c53e/public/embed-bloomlibrary.js#L64)):*
> ```JavaScript
>         const searchParamsFromData = new URLSearchParams(search);
>         searchParamsFromData.forEach((value, key) => {
>             if (key !== "blorg" && key.startsWith("bl-")) {
> ```

I recommend repeating some version of your comment from BlorgLink here:

`// Parameters beginning with "bl-" are defined as those to be forwarded`
___
*[public/embed-bloomlibrary.js, line 73 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/319#-MW_yf1E87wlojxG3hVH:-MW_yf1E87wlojxG3hVI:b-my7oro) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/d9b799983eed8509eab93628679c1a83ddd2c53e/public/embed-bloomlibrary.js#L73)):*
> ```JavaScript
> }
> 
> function parseAddBlorgLocationToUrlData(data) {
> ```

Would help to have a comment that says something like "Give {blah blah}, returns {path: foo, search: bar}"
___
*[src/components/BlorgLink.tsx, line 100 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/319#-MWa-OEtBWr0qkUOM7Kg:-MWa-OEtBWr0qkUOM7Kh:b-igh1y2) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/d9b799983eed8509eab93628679c1a83ddd2c53e/src/components/BlorgLink.tsx#L100)):*
> ```XML
> }
> 
> // Returns the query component (the part including/after the question mark) of the new "To" URL
> ```

Sorry, what's a "new To Url"?
___
*[src/components/EmbeddingHost.tsx, line 18 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/319#-MW_zIW609byaxWfW_px:-MW_zIW609byaxWfW_py:bid5ke4) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/d9b799983eed8509eab93628679c1a83ddd2c53e/src/components/EmbeddingHost.tsx#L18)):*
> ```XML
>     const domain = query.get("bl-domain");
> 
>     const cResponse1 = useContentful({
> ```

Odd variable name? `response` would work?

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/319)* status: 1 of 4 files reviewed, 5 unresolved discussions (waiting on @hatton and @sujeffreyl)

___
*[public/embed-bloomlibrary.js, line 78 at r2](https://reviewable.io/reviews/bloombooks/bloomlibrary2/319#-MWa5Ngh4rERmvhXcX2z:-MWa5Ngh4rERmvhXcX3-:b-sqsnv3) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/a09858d6ff771493abbe4d892e72d62316ba562b/public/embed-bloomlibrary.js#L78)):*
> ```JavaScript
> // returns a tuple with:
> //   path = the part before the question mark, and
> //   search = the part including and after the question mark
> ```

Yeah sorry your comment here is just the part that didn't need commenting :-)  What I asked for was an example.  It must just be too obvious, and I'll see that once I understand!

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/319)* status: 1 of 4 files reviewed, 5 unresolved discussions (waiting on @hatton)

___
*[public/embed-bloomlibrary.js, line 64 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/319#-MW_yMpQ8gP80Z0dBaNC:-MWa16yDCfpU4Re8drR5:b-896fix) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/d9b799983eed8509eab93628679c1a83ddd2c53e/public/embed-bloomlibrary.js#L64)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I recommend repeating some version of your comment from BlorgLink here:

`// Parameters beginning with "bl-" are defined as those to be forwarded`
</blockquote></details>

Done.
___
*[public/embed-bloomlibrary.js, line 73 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/319#-MW_yf1E87wlojxG3hVH:-MWa1hqwCV9BtTMkV0RQ:b-896fix) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/d9b799983eed8509eab93628679c1a83ddd2c53e/public/embed-bloomlibrary.js#L73)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Would help to have a comment that says something like "Give {blah blah}, returns {path: foo, search: bar}"
</blockquote></details>

Done.
___
*[public/embed-bloomlibrary.js, line 78 at r2](https://reviewable.io/reviews/bloombooks/bloomlibrary2/319#-MWa5Ngh4rERmvhXcX2z:-MWaEK7-EWAXDaOCw0pn:b-896fix) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/a09858d6ff771493abbe4d892e72d62316ba562b/public/embed-bloomlibrary.js#L78)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Yeah sorry your comment here is just the part that didn't need commenting :-)  What I asked for was an example.  It must just be too obvious, and I'll see that once I understand!
</blockquote></details>

Done.
___
*[src/components/BlorgLink.tsx, line 100 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/319#-MWa-OEtBWr0qkUOM7Kg:-MWa32Nr5QYSNnQosozn:b-l6pdc0) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/d9b799983eed8509eab93628679c1a83ddd2c53e/src/components/BlorgLink.tsx#L100)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Sorry, what's a "new To Url"?
</blockquote></details>

Well, a "to" URL is the URL that goes into the "to" parameter of the MuiLink component.
___
*[src/components/EmbeddingHost.tsx, line 18 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/319#-MW_zIW609byaxWfW_px:-MWa1yUvDfTQDfacJMYp:b-ympgxa) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/d9b799983eed8509eab93628679c1a83ddd2c53e/src/components/EmbeddingHost.tsx#L18)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Odd variable name? `response` would work?
</blockquote></details>

Hmm. I can drop the 'c'?

Uh, I had the conundrum where I added a 2nd call to useContentful, and it currently does that automatic object destructuring thing, but then I would have two variables with the same name, and since I need to call both hooks at the beginning and there's conditional logic, I can't re-use variables for them, so... yeah :(

**Review by hatton — APPROVED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/319)* status: all files reviewed, 4 unresolved discussions (waiting on @hatton)

**Pull request merged**
