### PR TITLE
Update README (BL-9515)

### PR DESCRIPTION
**Pull request by jsubloom**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/502)

### CODE REVIEW

**Review by jsubloom — COMMENTED** [review]
See formatted preview here: https://github.com/jsubloom/BloomLibrary2/blob/updateReadme/README.md

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/502#-:-NS6plAM29YpKi5LWL88:bc06ezu)* status: 0 of 1 files reviewed, all discussions resolved

**Review by jsubloom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/502)* status: 0 of 1 files reviewed, 1 unresolved discussion

___
*[`README.md` line 69 at r1](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/502#-NS6px9K11tx_OTw-mc4:-NS6px9K11tx_OTw-mc5:b-phkw54) ([raw file](https://github.com/BloomBooks/BloomLibrary2/blob/1cc1835c9d27941c8b5c8a022da092c26c0aabad/README.md#L69)):*
> ```Markdown
> ```yarn build-dev``` (or ```yarn build```)
> 
> bloom-player will build it in its ```dist``` folder. Overwrite this project's ```node_modules/bloom-player/dist``` folder with the newly-build ```dist``` folder from bloom-player.  (Remember to restore the original ```dist``` folder when you're done)
> ```

Actually, not 100% sure about this step. Appreciate your review here.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
Thanks for doing this!

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/502#-:-NS7085IE9Qzgh-GKKAk:bxgavm9)* status: all files reviewed, 8 unresolved discussions (waiting on @jsubloom)

___
*[`README.md` line 1 at r1](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/502#-NS701TH4ptoqphywk5U:-NS701TH4ptoqphywk5V:bgdp00a) ([raw file](https://github.com/BloomBooks/BloomLibrary2/blob/1cc1835c9d27941c8b5c8a022da092c26c0aabad/README.md#L1)):*
> ```Markdown
> A web site for sharing literacy materials, especially templates for translation into minority languages.
> ```

I know github already has a link to the website, but it probably wants to be here, too.
___
*[`README.md` line 18 at r1](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/502#-NS7-F_Z87iH0fHcoGfM:-NS7-F_Z87iH0fHcoGfN:b-tofikt) ([raw file](https://github.com/BloomBooks/BloomLibrary2/blob/1cc1835c9d27941c8b5c8a022da092c26c0aabad/README.md#L18)):*
> ```Markdown
> 
> ### nodejs ###
> Once nvm has been installed for windows, run these commands in a command window to install the needed versions of nodejs. This needs to be done only once.
> ```

version



_Code quote:_
```Markdown
versions
```
___
*[`README.md` line 20 at r1](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/502#-NS6zooKBJbd1SMuzu4B:-NS6zooKBJbd1SMuzu4C:b-rkm1jj) ([raw file](https://github.com/BloomBooks/BloomLibrary2/blob/1cc1835c9d27941c8b5c8a022da092c26c0aabad/README.md#L20)):*
> ```Markdown
> Once nvm has been installed for windows, run these commands in a command window to install the needed versions of nodejs. This needs to be done only once.
> 
>     nvm install 1.2.3 # or whatever the version should be. Check "engines" field of package.json.
> ```

Maybe
`nvm install 18.15.0 # Check "engines" field of package.json for supported versions.`



_Code quote:_
```Markdown
nvm install 1.2.3 # or whatever the version should be. Check "engines" field of package.json.
```
___
*[`README.md` line 21 at r1](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/502#-NS7-78A6ODG8eLMpB0z:-NS7-78A6ODG8eLMpB1-:brvsalk) ([raw file](https://github.com/BloomBooks/BloomLibrary2/blob/1cc1835c9d27941c8b5c8a022da092c26c0aabad/README.md#L21)):*
> ```Markdown
> 
>     nvm install 1.2.3 # or whatever the version should be. Check "engines" field of package.json.
>     nvm list
> ```

I would remove unnecessary `nvm list`.
___
*[`README.md` line 25 at r1](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/502#-NS6zST3EcH4PVDpQkDW:-NS6zST3EcH4PVDpQkDX:bsf2qvt) ([raw file](https://github.com/BloomBooks/BloomLibrary2/blob/1cc1835c9d27941c8b5c8a022da092c26c0aabad/README.md#L25)):*
> ```Markdown
> The following command is also helpful to switch between node versions:
> 
>     nvm use 1.2.3 # or whatever the version should be. Check "engines" field of package.json.
> ```

Maybe 
`nvm use 1.2.3 # same version as above`



_Code quote:_
```Markdown
nvm use 1.2.3 # or whatever the version should be. Check "engines" field of package.json.
```
___
*[`README.md` line 28 at r1](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/502#-NS6zJ-PDaeyOfVszGjK:-NS6zJ-PDaeyOfVszGjL:bg483vf) ([raw file](https://github.com/BloomBooks/BloomLibrary2/blob/1cc1835c9d27941c8b5c8a022da092c26c0aabad/README.md#L28)):*
> ```Markdown
> 
> ### yarn install ###
> Finally, run yarn again in a command line (e.g. in VSCode) to install dependencies
> ```

I would just say,
"Run yarn in a"



_Suggestion:_
```Markdown
Finally, run yarn again in a
```
___
*[`README.md` line 34 at r1](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/502#-NS70VBg5-X2thFsJtgC:-NS70VBg5-X2thFsJtgD:b9p8vzw) ([raw file](https://github.com/BloomBooks/BloomLibrary2/blob/1cc1835c9d27941c8b5c8a022da092c26c0aabad/README.md#L34)):*
> ```Markdown
> ---
> 
> ## Building locally ##
> ```

Maybe 
`Running locally`



_Code quote:_
```Markdown
Building locally
```
___
*[`README.md` line 69 at r1](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/502#-NS6px9K11tx_OTw-mc4:-NS6ydSl5xXoImR9xdBL:b7ldg5t) ([raw file](https://github.com/BloomBooks/BloomLibrary2/blob/1cc1835c9d27941c8b5c8a022da092c26c0aabad/README.md#L69)):*
<details><summary><i>Previously, jsubloom wrote…</i></summary><blockquote>

Actually, not 100% sure about this step. Appreciate your review here.
</blockquote></details>

Seems right. But yarn link seems like the preferred method, so I would make that first.

**Review by jsubloom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/502)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @andrew-polk)

___
*[`README.md` line 1 at r1](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/502#-NS701TH4ptoqphywk5U:-NS7rB4e9-vj9RTgXKI_:b-896fix) ([raw file](https://github.com/BloomBooks/BloomLibrary2/blob/1cc1835c9d27941c8b5c8a022da092c26c0aabad/README.md#L1)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I know github already has a link to the website, but it probably wants to be here, too.
</blockquote></details>

Done.
___
*[`README.md` line 18 at r1](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/502#-NS7-F_Z87iH0fHcoGfM:-NS7rfSc3sW6WhDK4n6i:b-896fix) ([raw file](https://github.com/BloomBooks/BloomLibrary2/blob/1cc1835c9d27941c8b5c8a022da092c26c0aabad/README.md#L18)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

version
</blockquote></details>

Done.
___
*[`README.md` line 20 at r1](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/502#-NS6zooKBJbd1SMuzu4B:-NS7rpPECGS29P_k_XeQ:b-896fix) ([raw file](https://github.com/BloomBooks/BloomLibrary2/blob/1cc1835c9d27941c8b5c8a022da092c26c0aabad/README.md#L20)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Maybe
`nvm install 18.15.0 # Check "engines" field of package.json for supported versions.`
</blockquote></details>

Done.
___
*[`README.md` line 21 at r1](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/502#-NS7-78A6ODG8eLMpB0z:-NS7rouU2jA48seGMPwF:b-896fix) ([raw file](https://github.com/BloomBooks/BloomLibrary2/blob/1cc1835c9d27941c8b5c8a022da092c26c0aabad/README.md#L21)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I would remove unnecessary `nvm list`.
</blockquote></details>

Done.
___
*[`README.md` line 25 at r1](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/502#-NS6zST3EcH4PVDpQkDW:-NS7sCpm1mV8ivx1rSPI:buyvb94) ([raw file](https://github.com/BloomBooks/BloomLibrary2/blob/1cc1835c9d27941c8b5c8a022da092c26c0aabad/README.md#L25)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Maybe 
`nvm use 1.2.3 # same version as above`
</blockquote></details>

I'd prefer for this part to be standalone, so you wouldn't normally run the two commands one after the other.
___
*[`README.md` line 28 at r1](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/502#-NS6zJ-PDaeyOfVszGjK:-NS7sXa8C4kMqVY9JuUD:bdcv6l8) ([raw file](https://github.com/BloomBooks/BloomLibrary2/blob/1cc1835c9d27941c8b5c8a022da092c26c0aabad/README.md#L28)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I would just say,
"Run yarn in a"
</blockquote></details>

Good point.
___
*[`README.md` line 34 at r1](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/502#-NS70VBg5-X2thFsJtgC:-NS7scWMBFHliUHWH2Wl:bb6un1j) ([raw file](https://github.com/BloomBooks/BloomLibrary2/blob/1cc1835c9d27941c8b5c8a022da092c26c0aabad/README.md#L34)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Maybe 
`Running locally`
</blockquote></details>

Done
___
*[`README.md` line 69 at r1](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/502#-NS6px9K11tx_OTw-mc4:-NS7tpr576LHBDP2oJ0n:b-ucfknh) ([raw file](https://github.com/BloomBooks/BloomLibrary2/blob/1cc1835c9d27941c8b5c8a022da092c26c0aabad/README.md#L69)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Seems right. But yarn link seems like the preferred method, so I would make that first.
</blockquote></details>

Thanks!

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/502)* status: all files reviewed, 1 unresolved discussion (waiting on @jsubloom)

___
*[`README.md` line 18 at r1](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/502#-NS7-F_Z87iH0fHcoGfM:-NS7vzTA9guMR5-7UUy-:b5sxwno) ([raw file](https://github.com/BloomBooks/BloomLibrary2/blob/1cc1835c9d27941c8b5c8a022da092c26c0aabad/README.md#L18)):*
<details><summary><i>Previously, jsubloom wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry; I'm not seeing this change. 
"needed versions" => "needed version"

**Review by jsubloom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/502)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`README.md` line 18 at r1](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/502#-NS7-F_Z87iH0fHcoGfM:-NS7wwFQ7KFf01WobmZN:b84raal) ([raw file](https://github.com/BloomBooks/BloomLibrary2/blob/1cc1835c9d27941c8b5c8a022da092c26c0aabad/README.md#L18)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Sorry; I'm not seeing this change. 
"needed versions" => "needed version"
</blockquote></details>

My bad, I don't know where it disappeared to.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/502)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jsubloom)

**Pull request merged**
