### PR TITLE
[WIP]BL-9252 localize Topics

### PR DESCRIPTION
**Pull request by gmartin7**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/217)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/217)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[src/components/CollectionSubsetPage.tsx, line 45 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/217#-MMSh7ym4Yiz9VYgPNbT:-MMSh7ym4Yiz9VYgPNbU:b-ydtzl1) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/409be2f62836a99503273ad0adbf6e1f400b978e/src/components/CollectionSubsetPage.tsx#L45)):*
> ```XML
>                     break;
>                 case "topic":
>                     // TODO: Figure out a way to localize the topic name here.
> ```

I think this is part of this card, right?

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/217)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[src/components/CollectionSubsetPage.tsx, line 45 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/217#-MMSh7ym4Yiz9VYgPNbT:-MMSq4c633RKPvGT-0bf:b-kp3g15) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/409be2f62836a99503273ad0adbf6e1f400b978e/src/components/CollectionSubsetPage.tsx#L45)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think this is part of this card, right?
</blockquote></details>

One possible way forward is to load the values into a "CachedTable". See App.tsx where we have CachedTables for non hook and CachedTablesContext for hooks.
Currently all those load from parse. Not sure what other complications there will be for this case, but that is an idea to get you started, anyway.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/217)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/components/CollectionSubsetPage.tsx, line 45 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/217#-MMSh7ym4Yiz9VYgPNbT:-MMXA65bEWHjY_TPh7AK:b-xtmltn) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/409be2f62836a99503273ad0adbf6e1f400b978e/src/components/CollectionSubsetPage.tsx#L45)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

One possible way forward is to load the values into a "CachedTable". See App.tsx where we have CachedTables for non hook and CachedTablesContext for hooks.
Currently all those load from parse. Not sure what other complications there will be for this case, but that is an idea to get you started, anyway.
</blockquote></details>

Done. There was a React.Fragment at just the place I needed to insert my CachedTopicContext! :) Much better and I was able to localize topics here too.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/217)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/components/CollectionSubsetPage.tsx, line 45 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/217#-MMSh7ym4Yiz9VYgPNbT:-MMXCujPAidyC5y-Hhle:b-7g1x0v) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/409be2f62836a99503273ad0adbf6e1f400b978e/src/components/CollectionSubsetPage.tsx#L45)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Done. There was a React.Fragment at just the place I needed to insert my CachedTopicContext! :) Much better and I was able to localize topics here too.
</blockquote></details>

Although... for testing I haven't figured out how to arrive at this code!

**Comment by gmartin7** [comment]
Closing this PR as a better one is coming...

**Pull request closed without merging**
