### PR TITLE
BL-10249 Tweak UI of desktop BR link

### PR DESCRIPTION
**Pull request by gmartin7**
* also tweaked OSFeatures so simulating an iPhone in
   Chrome works correctly

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/359)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/359)* status: all files reviewed, 2 unresolved discussions (waiting on @gmartin7)

___
*[src/components/BookDetail/DownloadsGroup.tsx, line 194 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/359#-MhFn3YTAuAa5xGHL_jm:-MhFn3YTAuAa5xGHL_jn:b-c5lxiy) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/613c546978c25560c517cfda5b374a731c3db07d/src/components/BookDetail/DownloadsGroup.tsx#L194)):*
> ```
> index === 1
> ```
This feels just a little too fragile.
For example, it will no longer be true if we add another icon at the beginning.

Ideas: 
- add a new props to IArtifactUI
- set the icon to a new const called `NoIcon` or similar and then check if the icon is that.

But just checking... it isn't enough to just add flex-grow to the bloomPub icon and get rid of this spacer?
___
*[src/components/BookDetail/DownloadsGroup.tsx, line 217 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/359#-MhFoYIO5538ZGVY_jQz:-MhFoYIO5538ZGVY_jR-:b-jwxasz) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/613c546978c25560c517cfda5b374a731c3db07d/src/components/BookDetail/DownloadsGroup.tsx#L217)):*
> ```XML
>                                                 ? "default"
>                                                 : "pointer"};
>                                         `}
> ```

Should we just change the pointer for all disabled iconbuttons?

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/359)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[src/components/BookDetail/DownloadsGroup.tsx, line 194 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/359#-MhFn3YTAuAa5xGHL_jm:-MhJtr8DEpCnbm2RW_j_:b-1szqjl) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/613c546978c25560c517cfda5b374a731c3db07d/src/components/BookDetail/DownloadsGroup.tsx#L194)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> index === 1
> ```
This feels just a little too fragile.
For example, it will no longer be true if we add another icon at the beginning.

Ideas: 
- add a new props to IArtifactUI
- set the icon to a new const called `NoIcon` or similar and then check if the icon is that.

But just checking... it isn't enough to just add flex-grow to the bloomPub icon and get rid of this spacer?
</blockquote></details>

I tried just adding `flex-grow` to the existing icon and it wasn't satisfactory. I agree the `index === 1` was too fragile. How about setting the `alt` string to "noIcon"? It's rather unlikely that the `alt` string would ever need to have that value otherwise.
___
*[src/components/BookDetail/DownloadsGroup.tsx, line 217 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/359#-MhFoYIO5538ZGVY_jQz:-MhK-Hvi7Cqdn_wtiMRv:bsdshal) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/613c546978c25560c517cfda5b374a731c3db07d/src/components/BookDetail/DownloadsGroup.tsx#L217)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Should we just change the pointer for all disabled iconbuttons?
</blockquote></details>

Yeah. Likely a good idea. In fact, while I'm at it why don't I do the same for the Feature icons too.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/359)* status: all files reviewed, 2 unresolved discussions (waiting on @gmartin7)

___
*[src/components/BookDetail/DownloadsGroup.tsx, line 194 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/359#-MhFn3YTAuAa5xGHL_jm:-MhKy_tN0M8BwoVefJp7:bpyvwn1) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/613c546978c25560c517cfda5b374a731c3db07d/src/components/BookDetail/DownloadsGroup.tsx#L194)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

I tried just adding `flex-grow` to the existing icon and it wasn't satisfactory. I agree the `index === 1` was too fragile. How about setting the `alt` string to "noIcon"? It's rather unlikely that the `alt` string would ever need to have that value otherwise.
</blockquote></details>

Hm. I think that means a screen reader will try to read that.
And maybe it will show that as a tooltip, too.
___
*[src/components/BookDetail/DownloadsGroup.tsx, line 217 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/359#-MhFoYIO5538ZGVY_jQz:-MhKySFO2pD94-gl1Ixx:b-a7exyp) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/613c546978c25560c517cfda5b374a731c3db07d/src/components/BookDetail/DownloadsGroup.tsx#L217)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Yeah. Likely a good idea. In fact, while I'm at it why don't I do the same for the Feature icons too.
</blockquote></details>

Can't do it for features because those navigate whether or not they are disabled.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/359)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[src/components/BookDetail/DownloadsGroup.tsx, line 194 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/359#-MhFn3YTAuAa5xGHL_jm:-MhP3brO5IHlOl8gV9Rw:btuxs4q) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/613c546978c25560c517cfda5b374a731c3db07d/src/components/BookDetail/DownloadsGroup.tsx#L194)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Hm. I think that means a screen reader will try to read that.
And maybe it will show that as a tooltip, too.
</blockquote></details>

Had to go with the new optional prop on `IArtifactUI`. I tried the new const approach and couldn't get it to work.
___
*[src/components/BookDetail/DownloadsGroup.tsx, line 217 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/359#-MhFoYIO5538ZGVY_jQz:-MhP0AmW9JDUHY6Ig7fZ:baxl7z0) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/613c546978c25560c517cfda5b374a731c3db07d/src/components/BookDetail/DownloadsGroup.tsx#L217)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Can't do it for features because those navigate whether or not they are disabled.
</blockquote></details>

Ah. OK. Reverting...

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/359)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Pull request merged**
