### PR TITLE
BL-10850 Fix brandingProjectName search

### PR DESCRIPTION
**Pull request by gmartin7**
* added 'facet' for brandingProjectName

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/401)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/401)* status: all files reviewed, 2 unresolved discussions (waiting on @gmartin7)

___
*[src/connection/LibraryQueryHooks.ts, line 1121 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/401#-MtibGvi6XDhPau1h0oe:-MtibGvi6XDhPau1h0of:b-iaj19f) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/c3a43a3186e0fb8648df564a6c6f406191826514/src/connection/LibraryQueryHooks.ts#L1121)):*
> ```XML
>                 .split(":")
>                 .map((p) => p.trim());
>             switch (facetLabel) {
> ```

If it is as easy as I think it is -- see below -- let's add `branding` as an alias.

I think we just add `branding` to the facet list above and then add
`if (facetLabel === 'branding') facetLabel = 'brandingProjectName';`
and then make facetLabel a `let` instead of `const`.
___
*[src/connection/LibraryQueryHooks.ts, line 1377 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/401#-MticY7y-oqM1TkHawVK:-MticY7y-oqM1TkHawVL:br3zb8m) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/c3a43a3186e0fb8648df564a6c6f406191826514/src/connection/LibraryQueryHooks.ts#L1377)):*
> ```XML
>     }
>     if (f.brandingProjectName) {
>         delete params.where.brandingProjectName;
> ```

What good does it do to delete it if we're just assigning it on the next line?
Can't the delete statements be removed?

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/401)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[src/connection/LibraryQueryHooks.ts, line 1121 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/401#-MtibGvi6XDhPau1h0oe:-MtigGK5E3kG4yj90nLP:bxp2cxx) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/c3a43a3186e0fb8648df564a6c6f406191826514/src/connection/LibraryQueryHooks.ts#L1121)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

If it is as easy as I think it is -- see below -- let's add `branding` as an alias.

I think we just add `branding` to the facet list above and then add
`if (facetLabel === 'branding') facetLabel = 'brandingProjectName';`
and then make facetLabel a `let` instead of `const`.
</blockquote></details>

Done. Well, we needed a mod in `splitString()` too, but easy enough. We lose the fancy spread, since one is `let` and the other `const`, but oh well.
___
*[src/connection/LibraryQueryHooks.ts, line 1377 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/401#-MticY7y-oqM1TkHawVK:-Mtinnhf0vQxUzDz9xL1:b-e37ii8) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/c3a43a3186e0fb8648df564a6c6f406191826514/src/connection/LibraryQueryHooks.ts#L1377)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

What good does it do to delete it if we're just assigning it on the next line?
Can't the delete statements be removed?
</blockquote></details>

I'm not sure how to test the filter part, but I've deleted the deletes at least for now.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/401)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

___
*[src/connection/LibraryQueryHooks.ts, line 1377 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/401#-MticY7y-oqM1TkHawVK:-Mtiw053-DlwJtyb_3lf:b-chaf6f) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/c3a43a3186e0fb8648df564a6c6f406191826514/src/connection/LibraryQueryHooks.ts#L1377)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

I'm not sure how to test the filter part, but I've deleted the deletes at least for now.
</blockquote></details>

Sent you a test collection in flowdock.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/401)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

___
*[src/connection/LibraryQueryHooks.ts, line 1377 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/401#-MticY7y-oqM1TkHawVK:-MtixOXUAA_5zGxlyYv4:b-218bia) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/c3a43a3186e0fb8648df564a6c6f406191826514/src/connection/LibraryQueryHooks.ts#L1377)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Sent you a test collection in flowdock.
</blockquote></details>

Seems to work fine.

**Pull request merged**
