### PR TITLE
BL-9999 When harvest failed because of font, give a link to the form

### PR DESCRIPTION
**Pull request by hatton**
screenshot: https://issues.bloomlibrary.org/youtrack/issue/BL-9999

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/338)

### CODE REVIEW

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/338)* status: all files reviewed, 3 unresolved discussions (waiting on @hatton)

___
*[src/components/BlorgLink.tsx, line 33 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/338#-MaTcNKk91S3zwYO7xFo:-MaTcNKk91S3zwYO7xFp:b-wub567) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/144d8b3faed8530543de98cc2a7688fbbfee13a8/src/components/BlorgLink.tsx#L33)):*
> ```XML
> 
>     if (isExternalOrEmail(props.href as string)) {
>         // Some links should open a new tab if we are embedded in an iframe.
> ```

If making other changes, consider tweaking the comment.
___
*[src/components/BookDetail/BookDetail.tsx, line 250 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/338#-MaTcTqs2EQqxNOh9R39:-MaTcTqs2EQqxNOh9R3A:b-h75kzp) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/7052ffedd5445accaadd63b81e84c3961aacb5bb/src/components/BookDetail/BookDetail.tsx#L250)):*
> ```XML
>                 </div>
>                 {showHarvesterWarning && (
>                     <IconButton
> ```

We seem to have lost something here that isn't obviously related to the change. Are there no other possible harvester warnings the user might want to see? Are we sure there will never be?
___
*[src/components/BookDetail/MissingFontBlock.tsx, line 27 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/338#-MaTbqd7-OlkpuLMsyjH:-MaTbqd8CD5gWxy6ymsm:b-ckydl7) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/144d8b3faed8530543de98cc2a7688fbbfee13a8/src/components/BookDetail/MissingFontBlock.tsx#L27)):*
> ```XML
>                     color="primary"
>                     href={`https://docs.google.com/forms/d/e/1FAIpQLSeo_lwdTU0JY4Nw1zlo1LCceXkLBWcATfWItnS7FqX5Aa3NUg/viewform?usp=pp_url&entry.1604864976=${window.location.href}&entry.1767307754=${n}`}
>                 >
> ```

Shouldn't each have a key?

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/338)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[src/components/BlorgLink.tsx, line 33 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/338#-MaTcNKk91S3zwYO7xFo:-MaTdaVo78vrci70n7v2:b-896fix) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/144d8b3faed8530543de98cc2a7688fbbfee13a8/src/components/BlorgLink.tsx#L33)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

If making other changes, consider tweaking the comment.
</blockquote></details>

Done.
___
*[src/components/BookDetail/BookDetail.tsx, line 250 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/338#-MaTcTqs2EQqxNOh9R39:-MaTdbYaB5Xa5xfzNv9I:b-4z6gln) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/7052ffedd5445accaadd63b81e84c3961aacb5bb/src/components/BookDetail/BookDetail.tsx#L250)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

We seem to have lost something here that isn't obviously related to the change. Are there no other possible harvester warnings the user might want to see? Are we sure there will never be?
</blockquote></details>

Yes. What was there was a different approach. Errors other than missing fonts still show in artifacts panel:


___
*[src/components/BookDetail/MissingFontBlock.tsx, line 27 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/338#-MaTbqd7-OlkpuLMsyjH:-MaTehNy7eHVbkNEfUEg:b-phck) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/144d8b3faed8530543de98cc2a7688fbbfee13a8/src/components/BookDetail/MissingFontBlock.tsx#L27)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Shouldn't each have a key?
</blockquote></details>

Sorry, what sort of key do you have in mind?

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/338)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @hatton and @JohnThomson)

___
*[src/components/BookDetail/MissingFontBlock.tsx, line 27 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/338#-MaTbqd7-OlkpuLMsyjH:-MaTkRMn5F8QYUnfrQFH:b-y3l2k3) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/144d8b3faed8530543de98cc2a7688fbbfee13a8/src/components/BookDetail/MissingFontBlock.tsx#L27)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Sorry, what sort of key do you have in mind?
</blockquote></details>

When you display a list in React using a map, IIRC you are supposed to give each item a distinct key attribute. I think it's to benefit performance when the list changes, so may be quite irrelevant here, where I don't think the list will ever change during the lifetime of the parent.

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/338)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @hatton and @JohnThomson)

___
*[src/components/BookDetail/MissingFontBlock.tsx, line 27 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/338#-MaTbqd7-OlkpuLMsyjH:-MaTl7aqCy_XxuPLDMbC:b-h6gndk) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/144d8b3faed8530543de98cc2a7688fbbfee13a8/src/components/BookDetail/MissingFontBlock.tsx#L27)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

When you display a list in React using a map, IIRC you are supposed to give each item a distinct key attribute. I think it's to benefit performance when the list changes, so may be quite irrelevant here, where I don't think the list will ever change during the lifetime of the parent.
</blockquote></details>

https://reactjs.org/docs/lists-and-keys.html

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/338)* status: 3 of 7 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/components/BookDetail/BookDetail.tsx, line 250 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/338#-MaTcTqs2EQqxNOh9R39:-MaTellx9jNTbtq0Alxe:b-896fix) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/7052ffedd5445accaadd63b81e84c3961aacb5bb/src/components/BookDetail/BookDetail.tsx#L250)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Yes. What was there was a different approach. Errors other than missing fonts still show in artifacts panel:



</blockquote></details>

Done.
___
*[src/components/BookDetail/MissingFontBlock.tsx, line 27 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/338#-MaTbqd7-OlkpuLMsyjH:-MaTs0255Ab9sz2raYN4:b-ft9mnp) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/144d8b3faed8530543de98cc2a7688fbbfee13a8/src/components/BookDetail/MissingFontBlock.tsx#L27)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

https://reactjs.org/docs/lists-and-keys.html
</blockquote></details>

Oh of course, sorry. I was focused on the href being constructed here, thinking you wanted some kind of key on it. Looking at the console, I found a 2 other warnings to fix.

**Review by JohnThomson — APPROVED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/338)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hatton)

**Review by JohnThomson — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/338)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hatton)

**Pull request merged**
