### PR TITLE
Add two statistics columns to grid for display and export (BL-9602)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
Any remaining statistics columns could be added easily if wanted.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/311)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/311)* status: all files reviewed, 4 unresolved discussions (waiting on @StephenMcConnel)

___
*[src/components/Grid/GridExport.ts, line 52 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/311#-MUyPmv-5bb4CwOoFJFk:-MUyPmv-5bb4CwOoFJFl:b-vt7gj0) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/30d58aa30c585114ebaba7ba2b771fe0119bada7/src/components/Grid/GridExport.ts#L52)):*
> ```
> Promise.all([bookData, bookStats]).then(([bookData, bookStats])
> ```
I think the results want a different name.
So, something like
> ```
> Promise.all([bookData, bookStats]).then(([bookDataResults, bookStatsResults])
> ```
or
> ```
> Promise.all([bookDataPromise, bookStatsPromise]).then(([bookData, bookStats])
> ```
?
___
*[src/connection/LibraryQueries.ts, line 62 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/311#-MUyRPPLBoKmFwMNy6HL:-MUyRPPLBoKmFwMNy6HM:bs5787a) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/30d58aa30c585114ebaba7ba2b771fe0119bada7/src/connection/LibraryQueries.ts#L62)):*
> ```XML
>             },
>         }
>     );
> ```

I still think we need to work on not duplicating these for hook and non-hook. But I'll create a separate card.
___
*[src/connection/LibraryQueryHooks.ts, line 384 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/311#-MUyREHKEm7KCAoqpJQT:-MUyREHL84g4dmcG-eAJ:bxorfrj) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/30d58aa30c585114ebaba7ba2b771fe0119bada7/src/connection/LibraryQueryHooks.ts#L384)):*
> ```XML
>         const book: Book = bookFromIdMap[statRow.bookinstanceid];
>         if (book) {
>             book.stats.title = statRow.booktitle;
> ```

Any way to extract this logic and reuse it from useGetBookStats?
But we have to be careful not to pull the stats code into the main bundle for performance reasons.
___
*[src/model/Book.ts, line 123 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/311#-MUyPR05CU1thIIBqRgn:-MUyPR05CU1thIIBqRgo:bxtw4ez) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/30d58aa30c585114ebaba7ba2b771fe0119bada7/src/model/Book.ts#L123)):*
<details><summary><i alt="summary">Quoted 15 lines of code…</i></summary>

> ```
>     {
>         title: "",
>         branding: "",
>         questions: 0,
>         quizzesTaken: 0,
>         meanCorrect: 0,
>         medianCorrect: 0,
>         language: "",
>         startedCount: 0,
>         finishedCount: 0,
>         shellDownloads: 0,
>         pdfDownloads: 0,
>         epubDownloads: 0,
>         bloomPubDownloads: 0,
>     };
> ```
</details>

Maybe this would be better as an exported const where IBookStat is?
`DefaultBookStat`? `InitialBookStat`?
What do you think?

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/311)* status: all files reviewed, 4 unresolved discussions (waiting on @andrew-polk)

___
*[src/components/Grid/GridExport.ts, line 52 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/311#-MUyPmv-5bb4CwOoFJFk:-MUzEwpC9wWqkapezhfc:b6vd8v5) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/30d58aa30c585114ebaba7ba2b771fe0119bada7/src/components/Grid/GridExport.ts#L52)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> Promise.all([bookData, bookStats]).then(([bookData, bookStats])
> ```
I think the results want a different name.
So, something like
> ```
> Promise.all([bookData, bookStats]).then(([bookDataResults, bookStatsResults])
> ```
or
> ```
> Promise.all([bookDataPromise, bookStatsPromise]).then(([bookData, bookStats])
> ```
?
</blockquote></details>

I think I prefer the latter renaming.  The compiler doesn't need new names, but I can see where humans would benefit.
___
*[src/connection/LibraryQueries.ts, line 62 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/311#-MUyRPPLBoKmFwMNy6HL:-MUzFBty58lpJHo_IdhS:b2nhktp) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/30d58aa30c585114ebaba7ba2b771fe0119bada7/src/connection/LibraryQueries.ts#L62)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I still think we need to work on not duplicating these for hook and non-hook. But I'll create a separate card.
</blockquote></details>

OK.
___
*[src/connection/LibraryQueryHooks.ts, line 384 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/311#-MUyREHKEm7KCAoqpJQT:-MUzMMt1-ZUEadKxETGe:b-896fix) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/30d58aa30c585114ebaba7ba2b771fe0119bada7/src/connection/LibraryQueryHooks.ts#L384)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Any way to extract this logic and reuse it from useGetBookStats?
But we have to be careful not to pull the stats code into the main bundle for performance reasons.
</blockquote></details>

Done.
___
*[src/model/Book.ts, line 123 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/311#-MUyPR05CU1thIIBqRgn:-MUzNvXGAcO_Cfv3QTEd:b-6ujlpe) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/30d58aa30c585114ebaba7ba2b771fe0119bada7/src/model/Book.ts#L123)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
>     {
>         title: "",
>         branding: "",
>         questions: 0,
>         quizzesTaken: 0,
>         meanCorrect: 0,
>         medianCorrect: 0,
>         language: "",
>         startedCount: 0,
>         finishedCount: 0,
>         shellDownloads: 0,
>         pdfDownloads: 0,
>         epubDownloads: 0,
>         bloomPubDownloads: 0,
>     };
> ```
Maybe this would be better as an exported const where IBookStat is?
`DefaultBookStat`? `InitialBookStat`?
What do you think?
</blockquote></details>

I don't think this would be safe.  If used more than once, changing an individual value in the IBookStat object would change it in both places as I understand const as it applies to objects in TypeScript. What I mean is:

const a : IBookStat = DefaultBookStat;
const b: IBookStat = DefaultBookStat;
a.title = "Book A";
b.title = "Book B";

What does a.title equal now?  I think it equals "Book B" because a and b essentially both point to DefaultBookStat.  Now I could be wrong, of course.
Perhaps a function that returns an object would effectively create a new copy each time, avoiding this problem?

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/311)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @andrew-polk and @StephenMcConnel)

___
*[src/connection/LibraryQueries.ts, line 62 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/311#-MUyRPPLBoKmFwMNy6HL:-MV2BKtp3_EBPFHkcINU:b-yvono0) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/30d58aa30c585114ebaba7ba2b771fe0119bada7/src/connection/LibraryQueries.ts#L62)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

OK.
</blockquote></details>

As discussed this morning, we want to go ahead and re-engineer this now.
Happy to discuss if helpful.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/311)* status: all files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

___
*[src/model/Book.ts, line 123 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/311#-MUyPR05CU1thIIBqRgn:-MV2REWk1K5Uj3PHAIE1:bp2ddt3) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/30d58aa30c585114ebaba7ba2b771fe0119bada7/src/model/Book.ts#L123)):*
> I don't think this would be safe

Good call. I think you're right.

> Perhaps a function that returns an object would effectively create a new copy each time, avoiding this problem?

Yes, sounds right.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/311)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @StephenMcConnel)

___
*[src/connection/LibraryQueries.ts, line 62 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/311#-MUyRPPLBoKmFwMNy6HL:-MV3LocCBBdLC3Xwb4n_:bnu9pda) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/30d58aa30c585114ebaba7ba2b771fe0119bada7/src/connection/LibraryQueries.ts#L62)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

As discussed this morning, we want to go ahead and re-engineer this now.
Happy to discuss if helpful.
</blockquote></details>

The code for sharing the axios calls has been implemented.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/311)* status: 2 of 7 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[src/model/Book.ts, line 123 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/311#-MUyPR05CU1thIIBqRgn:-MV3ORTG6XnhZouzvrUD:b-896fix) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/30d58aa30c585114ebaba7ba2b771fe0119bada7/src/model/Book.ts#L123)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> I don't think this would be safe

Good call. I think you're right.

> Perhaps a function that returns an object would effectively create a new copy each time, avoiding this problem?

Yes, sounds right.
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/311)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
