### PR TITLE
Handle very long titles better in download dialog (BL-9847)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/435)

### CODE REVIEW

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/435)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @hatton and @StephenMcConnel)

___
*[src/components/BookDetail/DownloadPreflightDialog.tsx, line 48 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/435#-MzH0-oH5MFsVvAHXv_P:-MzH0-oH5MFsVvAHXv_Q:bknpdrm) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/ac37177c11390460a05c8431234bfa439ef7acfd/src/components/BookDetail/DownloadPreflightDialog.tsx#L48)):*
> ```XML
>             </DialogTitle>
>             <DialogContent>
>                 <div>
> ```

The diff here is worthless. can you confirm that all you did was wrap in a div? Would be worth a comment else someone (like me) will remove it in the future, check that it didn't obviously break, and then the world will be sad.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/435)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[src/components/BookDetail/DownloadPreflightDialog.tsx, line 48 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/435#-MzH0-oH5MFsVvAHXv_P:-MzH9u0897ArVjd2gFYT:b-4gczb0) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/ac37177c11390460a05c8431234bfa439ef7acfd/src/components/BookDetail/DownloadPreflightDialog.tsx#L48)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

The diff here is worthless. can you confirm that all you did was wrap in a div? Would be worth a comment else someone (like me) will remove it in the future, check that it didn't obviously break, and then the world will be sad.
</blockquote></details>

Yes, all I added was wrapping in a div element.  I've added a comment to explain the presence of the div, linking to the issue.
(I also changed the div to wrap the following element instead as originally suggested by Andrew.)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> Dismissed @hatton from a discussion.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/435)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk and @hatton)

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/435)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk and @hatton)

**Review by andrew-polk — APPROVED** [review]
> Dismissed @StephenMcConnel from a discussion.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/435)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
