### PR TITLE
Fix requirements link and only show release notes link if exists

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/166)

### CODE REVIEW

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/166)* status: 0 of 1 files reviewed, all discussions resolved

___
*[src/components/WindowsInstallerDownloads.tsx, line 81 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/166#-MGtE5Vh4rd663jAuk6m:-MGtE5Vh4rd663jAuk6n:b-50q7qb) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/f0d9e44f9c8a85dda03c85769f8a1eca2988cd28/src/components/WindowsInstallerDownloads.tsx#L81)):*
> ```
> "/page/create/bloom-windows-requirements"
> ```
The most important part of this change is adding the `/` at the beginning of this href.

**Review by sujeffreyl — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/166)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/components/WindowsInstallerDownloads.tsx, line 77 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/166#-MGtQHHMDqdAfmaUNfwu:-MGtQHHMDqdAfmaUNfwv:b-a0hmig) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/f0d9e44f9c8a85dda03c85769f8a1eca2988cd28/src/components/WindowsInstallerDownloads.tsx#L77)):*
> ```
> href={info.releaseNotes}
> ```
Does this need quotes surrounding releaseNotes, or does the variable itself include the quotes?

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/166)* status: all files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

___
*[src/components/WindowsInstallerDownloads.tsx, line 77 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/166#-MGtQHHMDqdAfmaUNfwu:-MGthKf20An-kozN-ANp:bdh47zt) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/f0d9e44f9c8a85dda03c85769f8a1eca2988cd28/src/components/WindowsInstallerDownloads.tsx#L77)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

> ```
> href={info.releaseNotes}
> ```
Does this need quotes surrounding releaseNotes, or does the variable itself include the quotes?
</blockquote></details>

Looks like the React component must insert the quote marks when it creates the html `a` element.

**Review by sujeffreyl — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/166)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
