### PR TITLE
BL-9317 Adjust to phone screens (wip)

### PR DESCRIPTION
**Pull request by hatton**
https://issues.bloomlibrary.org/youtrack/issue/BL-9317
Move cards to the new left-aligned, space-saving design
Banner sizing
Card sizing
Cards spacing
Clarified the names around the 2 versions of cardswiper

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/260)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
Looks good. A few comments.

> Reviewed 19 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/260#-:-MQryqef8F0oPk_EVb7A:b95remr)* status: all files reviewed, 9 unresolved discussions (waiting on @hatton)

___
*[src/responsiveUtilities.ts, line 7 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/260#-MQrpiCR0sbBUrOUdpJb:-MQrpiCS0J16R9rDHyrT:bb8s8tc) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/de1916e17d4a7371f06fd5e3e377294842a40f00/src/responsiveUtilities.ts#L7)):*
> ```
> Initialize state with undefined width/height
> ```
I'm missing something or this comment is out of date.
___
*[src/responsiveUtilities.ts, line 39 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/260#-MQrqGbAEq2CRP8zzdnB:-MQrqGbAEq2CRP8zzdnC:b-yyge3r) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/de1916e17d4a7371f06fd5e3e377294842a40f00/src/responsiveUtilities.ts#L39)):*
> ```XML
> export function useSmallScreen() {
>     const theme = useTheme();
>     // I don't get how this can be so large: return
> ```

Is this comment out of place/obsolete?
___
*[src/responsiveUtilities.ts, line 59 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/260#-MQrsPK5DURnBNPsMLpK:-MQrsPK5DURnBNPsMLpL:b-91ffbe) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/de1916e17d4a7371f06fd5e3e377294842a40f00/src/responsiveUtilities.ts#L59)):*
> ```XML
>     return (
>         smallest: number | string,
>         largest: number | string
> ```

I think this would be more clear as smallScreenValue and largeScreenValue, especially since there are cases when the former is larger than the latter.
___
*[src/components/CardGroup.tsx, line 52 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/260#-MQrtf5tC_IxKXvrCg_F:-MQrtf5u7yufAe1AmoD7:b84oc17) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/de1916e17d4a7371f06fd5e3e377294842a40f00/src/components/CardGroup.tsx#L52)):*
> ```XML
>                         css={css`
>                             font-size: ${getResponsiveChoice(10, 14)}pt;
>                         `}
> ```

Seems like we might want to extract this to a common method, perhaps in ResponsiveUtilities or theme.
Same values are used in quite a few places. Some of them it seems we would definitely want the same.
___
*[src/components/CardSwiper.tsx, line 80 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/260#-MQruf-DBqcXk5Nw3oHI:-MQruf-DBqcXk5Nw3oHJ:bbejudl) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/de1916e17d4a7371f06fd5e3e377294842a40f00/src/components/CardSwiper.tsx#L80)):*
> ```
>     // If too large, we'll get blank areas. If too small, we just compute
>     // more than we need to.
>     // If too small, when you scroll swiper, it is "jumpy".
> ```
I think the first sentence was intended to get replaced by the second?
___
*[src/components/CheapCard.tsx, line 21 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/260#-MQrvkJh2PThuq4uba3D:-MQrvkJi3CAOqKu7N6T5:bfr5hxb) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/de1916e17d4a7371f06fd5e3e377294842a40f00/src/components/CheapCard.tsx#L21)):*
> ```XML
> export const CheapCard: React.FunctionComponent<IProps> = (props) => {
>     const url = getUrlForTarget(props.target || "");
>     const getResponsiveChoice = useResponsiveChoice();
> ```

Not used.
___
*[src/components/RowOfCards.tsx, line 53 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/260#-MQrx38R2w5KDwpFI-st:-MQrx38R2w5KDwpFI-su:b-t73tsj) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/de1916e17d4a7371f06fd5e3e377294842a40f00/src/components/RowOfCards.tsx#L53)):*
> ```XML
>     // );
>     const childCollections = props.collection.childCollections;
>     console.log(`${props.collection.label} ${props.collection.layout}`);
> ```

leftover console.log
___
*[src/components/banners/Blurb.tsx, line 23 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/260#-MQrxREG0cY9WrFdEFIC:-MQrxREHA09dP3fICdfK:bfr5hxb) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/de1916e17d4a7371f06fd5e3e377294842a40f00/src/components/banners/Blurb.tsx#L23)):*
> ```XML
> }> = (props) => {
>     const l10n = useIntl();
>     const getResponsiveChoice = useResponsiveChoice();
> ```

Not used.
___
*[src/connection/GetQueryResultsUI.tsx, line 10 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/260#-MQrxZ-Y30MTtZwyCVin:-MQrxZ-Y30MTtZwyCVio:b9sej4t) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/de1916e17d4a7371f06fd5e3e377294842a40f00/src/connection/GetQueryResultsUI.tsx#L10)):*
> ```XML
>             {/* without this we don't get line and then the screen jumps */}
>             {"-"}
>         </div>
> ```

This seems like an unfortunate step backwards (to go from a gray rectangle to a dash.
Can we make it the smaller size? Then at least we don't get a jump on mobile and get a smaller jump on desktop.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 19 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/260)* status: all files reviewed, 9 unresolved discussions (waiting on @hatton)

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/260)* status: all files reviewed, 9 unresolved discussions (waiting on @andrew-polk)

___
*[src/responsiveUtilities.ts, line 7 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/260#-MQrpiCR0sbBUrOUdpJb:-MQwls1f8VbLCGOAA7n-:bitjc2d) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/de1916e17d4a7371f06fd5e3e377294842a40f00/src/responsiveUtilities.ts#L7)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> Initialize state with undefined width/height
> ```
I'm missing something or this comment is out of date.
</blockquote></details>

yeah bad copy/paste job.
___
*[src/responsiveUtilities.ts, line 39 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/260#-MQrqGbAEq2CRP8zzdnB:-MQwmK6-2zN4Ig4tiNr1:b-886gsx) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/de1916e17d4a7371f06fd5e3e377294842a40f00/src/responsiveUtilities.ts#L39)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is this comment out of place/obsolete?
</blockquote></details>

Fixed
___
*[src/responsiveUtilities.ts, line 59 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/260#-MQrsPK5DURnBNPsMLpK:-MQwmWSBEVT9y7Hx9oPs:b-62ymqr) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/de1916e17d4a7371f06fd5e3e377294842a40f00/src/responsiveUtilities.ts#L59)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think this would be more clear as smallScreenValue and largeScreenValue, especially since there are cases when the former is larger than the latter.
</blockquote></details>

Thx. Wrote that thinkin I would scale them responsively, but then abandoned that idea. 
___
*[src/components/CardGroup.tsx, line 52 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/260#-MQrtf5tC_IxKXvrCg_F:-MQwn-iW3dcbtrNv9G0j:b-h74azf) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/de1916e17d4a7371f06fd5e3e377294842a40f00/src/components/CardGroup.tsx#L52)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Seems like we might want to extract this to a common method, perhaps in ResponsiveUtilities or theme.
Same values are used in quite a few places. Some of them it seems we would definitely want the same.
</blockquote></details>

Yeah, I would review that the same way. But honestly I don't know how to do it yet, and prematurely joining them all is going to be worse. They happen to have the same values, but I'm not clear enough on it to get that a name and say everything has  have the same. It's an area to improve.

In a couple of the cases, these are bookcounts, and it bother me that these aren't the same component. I'm wondering if we need a layer above "cheap card", which both language cards and collection cards use, which captures what those have in common (e.g. a book count). But not there yet.
___
*[src/components/CardSwiper.tsx, line 80 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/260#-MQruf-DBqcXk5Nw3oHI:-MQwpbKPDNlnIHTGqooR:b738jn8) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/de1916e17d4a7371f06fd5e3e377294842a40f00/src/components/CardSwiper.tsx#L80)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
>     // If too large, we'll get blank areas. If too small, we just compute
>     // more than we need to.
>     // If too small, when you scroll swiper, it is "jumpy".
> ```
I think the first sentence was intended to get replaced by the second?
</blockquote></details>

no but I've made it clearer, thx.
___
*[src/components/CheapCard.tsx, line 21 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/260#-MQrvkJh2PThuq4uba3D:-MQwpiOGEyLv5ezRXYVw:b-896fix) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/de1916e17d4a7371f06fd5e3e377294842a40f00/src/components/CheapCard.tsx#L21)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Not used.
</blockquote></details>

Done.
___
*[src/components/RowOfCards.tsx, line 53 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/260#-MQrx38R2w5KDwpFI-st:-MQwpseCBPlLkiROL-dI:b-896fix) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/de1916e17d4a7371f06fd5e3e377294842a40f00/src/components/RowOfCards.tsx#L53)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

leftover console.log
</blockquote></details>

Done.
___
*[src/components/banners/Blurb.tsx, line 23 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/260#-MQrxREG0cY9WrFdEFIC:-MQwpxFt2pXUmL75OVCS:b-896fix) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/de1916e17d4a7371f06fd5e3e377294842a40f00/src/components/banners/Blurb.tsx#L23)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Not used.
</blockquote></details>

Done.
___
*[src/connection/GetQueryResultsUI.tsx, line 10 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/260#-MQrxZ-Y30MTtZwyCVin:-MQwqNONAGTOyzGrd3E4:b-xa90xk) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/de1916e17d4a7371f06fd5e3e377294842a40f00/src/connection/GetQueryResultsUI.tsx#L10)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This seems like an unfortunate step backwards (to go from a gray rectangle to a dash.
Can we make it the smaller size? Then at least we don't get a jump on mobile and get a smaller jump on desktop.
</blockquote></details>

Yeah. OK I spun this off to https://issues.bloomlibrary.org/youtrack/issue/BL-9396

**Review by andrew-polk — APPROVED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/260)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hatton)

**Pull request merged**
