### PR TITLE
Get and cache just the collections we need

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/269)

### CODE REVIEW

**Comment by JohnThomson** [comment]
OK, fixed

**Comment by JohnThomson** [comment]
And more problems...don't merge yet

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/269)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/model/Collections.tsx, line 142 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/269#-MR6ESuf1ngrdMV5NH2k:-MR6ESuf1ngrdMV5NH2l:b-x267e2) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/c33bbb81b80dafa077323e706c27e7b91b0f52a8/src/model/Collections.tsx#L142)):*
> ```
> alert("collection " + collectionName + " not found");
> ```
I would rather not use an alert unless it is the only way to alert the user.
Typically, if we ask for a collection which doesn't exist, we just get "Collection not found" on the screen. Does that happen in this case? If not, can we cause it to?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/269)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/model/Collections.tsx, line 142 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/269#-MR6ESuf1ngrdMV5NH2k:-MR6HCHi8qAyOG3HCbTK:b-k63oy9) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/c33bbb81b80dafa077323e706c27e7b91b0f52a8/src/model/Collections.tsx#L142)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> alert("collection " + collectionName + " not found");
> ```
I would rather not use an alert unless it is the only way to alert the user.
Typically, if we ask for a collection which doesn't exist, we just get "Collection not found" on the screen. Does that happen in this case? If not, can we cause it to?
</blockquote></details>

Yes, it worked fine. Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/269)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/269)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/model/Collections.tsx, line 85 at r3](https://reviewable.io/reviews/bloombooks/bloomlibrary2/269#-MR6tBs7EyZon4EeKift:-MR6tBs7EyZon4EeKifu:brptzak) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/e35068420f52b870b50c5b96d20311d8bf0f2643/src/model/Collections.tsx#L85)):*
> ```XML
>                   // As of Jan 2021, we save about 17% by restricting fields this way. Replacing all the fields.* items with just "fields"
>                   // is also worth considering...we save 16% just by cutting out unused sys fields.
>                   select:
> ```

Yeah @johnthomson  I don't think 1% here is worth the time we'll spend chasing bugs. I'd just grab all the fields.

**Pull request merged**
