### PR TITLE
Fix mobx to use actions where needed

### PR DESCRIPTION
**Pull request by gmartin7**
* simplifies other code too

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/293)

### CODE REVIEW

**Review by StephenMcConnel — CHANGES_REQUESTED** [review]
Probably okay, but more actions are needed for the bulk-edit page to handle filters.

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/293#-:-MS-Yqcp2gzLAexxP_Mk:bwjdf2e)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Review by andrew-polk — COMMENTED** [review]
Is this needed for all observables? So that means a bunch of stuff on book, too.
But I don't think I understand the situation generally.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/293#-:-MS-fRND8yzTixCPvBM_:b1x3wrl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Review by gmartin7 — COMMENTED** [review]
@stephenmcconnel True, and I've pretty much finished that up, but @andrew-polk is right too, there's a bunch to do on Book.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/293#-:-MS-v6t_7sXUPAQwu_8-:blqptbq)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Review by gmartin7 — COMMENTED** [review]
But I may be able to do all of Book with a simple change... will look into it more tomorrow.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/293#-:-MS-wqdQ7G-93amx5VZm:b-ljth9j)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/293)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/293)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[src/App.tsx, line 24 at r2](https://reviewable.io/reviews/bloombooks/bloomlibrary2/293#-MS5-dv-AnhWMpGQL4XK:-MS5-dv01fxvLxTSu87p:b-4d9tds) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/d47237e384320cb8260796205073d8db2962fb22/src/App.tsx#L24)):*
> ```XML
> // of wrapping methods annotated as 'actions'.
> configure({ enforceActions: "never" });
> ```

I must admit I like this latest iteration the best so far.  :-)
Have you tried the other settings for enforceActions to see what happens?  (just curious)

**Pull request merged**
