### PR TITLE
BL-10823 Shrink H1 in mobile banners

### PR DESCRIPTION
**Pull request by gmartin7**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/392)

### CODE REVIEW

**Review by hatton — COMMENTED** [review]
Do you know why so much stuff is shown as changed in the diff, when it's not?

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/392#-:-MskXOYIE0lrqoYglNG_:b-1uhmhm)* status: 0 of 1 files reviewed, all discussions resolved

**Review by gmartin7 — COMMENTED** [review]
No idea!

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/392#-:-MskXxFEAqq647xskSyj:bnpi2a8)* status: 0 of 1 files reviewed, all discussions resolved

**Review by gmartin7 — COMMENTED** [review]
Actually, it looks like Blurb.tsx had a bunch of extra space characters at the end of lines that Prettier must have deleted.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/392#-:-MskZNom9_mf26qLpuL9:bptebgg)* status: 0 of 1 files reviewed, all discussions resolved

**Review by StephenMcConnel — COMMENTED** [review]
The github view has a control to "hide whitespace" in the diff, which then shows the actual differences.  I can't find any corresponding control inside Reviewable, which seems like a major lack.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/392#-:-MslEYxB4Dw0lS0JL2WT:b-3tfj3d)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Review by StephenMcConnel — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/392#-:-MslGAoD9bBOuB6BV1QN:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
