### PR TITLE
Add a Donate button to the Bloom Library footer (BL-11804)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/488)

### CODE REVIEW

**Review by JohnThomson — CHANGES_REQUESTED** [review]
I noticed one discrepancy: John's mockup has the Contentful icon right-aligned under the Github one in narrow mode, but yours does not.

Does everything adjust itself properly if the user issues the browser command to make things (or just text) bigger? For example, does the extra 50px of top margin grow (or not) by the same amount as the Donate button? Maybe it should be measured in a text-size-dependent unit like rem?

This approach will break if a translation of "Donate" runs to two lines (maybe some culture needs something like "Be so generous as to make a contribution," so I don't like it very much. But I don't know of a better way., short of using a typescript media query to actually put the Donate button in a different place in the HTML (i.e., before the row of links instead of part of it). I doubt it's worth switching to that, especially since you already did all this work.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/488#-:-NL20Pxa0x9vBXtAX9lb:b5650kh)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/components/Footer.tsx` line 13 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/488#-NL1zVmqAmZWP7KgHmWT:-NL1zVmqAmZWP7KgHmWU:b-7x4n94) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/b96b0616d54a609f9a17e7ff7227b75d27706237/src/components/Footer.tsx#L13)):*
> ```XML
> import { Button } from "@material-ui/core";
> 
> const narrowWidth = "475px"; // width at which footer layout must change
> ```

Will it need to change at a different width if it is being viewed in another language? (Or maybe we will just live with letting some buttons wrap their text in that case?)
___
*[`src/components/Footer.tsx` line 72 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/488#-NL21Jup1bGowlV2uBE2:-NL21JuqDPwa2kN0Zv4k:bpttljc) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/b96b0616d54a609f9a17e7ff7227b75d27706237/src/components/Footer.tsx#L72)):*
> ```XML
>                         position: absolute;
>                         right: 20px;
>                         bottom: 83px;
> ```

This is being pushed into the (increased) top margin of the parent row, so positioning it using bottom: seems risky. What if some of the other items in the row need to wrap and therefore get bigger?
___
*[`src/components/Footer.tsx` line 142 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/488#-NL1zKgDC98_LEyeaHUo:-NL1zKgE0BYnTDmPGeKa:b-jsj9bg) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/b96b0616d54a609f9a17e7ff7227b75d27706237/src/components/Footer.tsx#L142)):*
> ```XML
>                     position: absolute;
>                     top: 20px;
>                     right: 20px;
> ```

Unless it's inherited from somewhere, I don't see that this has bold text like the card says it should.
___
*[`src/components/Footer.tsx` line 196 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/488#-NL2-1WyDIi4MNKF-r3k:-NL2-1WyDIi4MNKF-r3l:b-m4qlpr) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/b96b0616d54a609f9a17e7ff7227b75d27706237/src/components/Footer.tsx#L196)):*
> ```XML
>                     @media (max-width: ${narrowWidth}) {
>                         margin-top: 45px; // allow space for absolutely positioned github button
>                     }
> ```

There's a lot more room, typically, on the last row...do you think it should really switch at the same max-width? John's mockup does seem to show the Github button moving when it doesn't really need to, so that might be right...I would have been inclined not to move it until it independently needs to. On small screens the less space the footer takes up the better! This might be something to ask JohnH.

**Review by StephenMcConnel — COMMENTED** [review]
Right-aligning the Contentful icon under the Github icon would require making the Contentful icon position: absolute as well as the Github icon.  I'm trying for a minimal change to existing elements.  I thought aligning the two buttons that shift out of the rows was more intuitive.
Things do seem to work right using the Ctrl-+ and Ctrl-- to zoom in and out in the browser.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/488#-:-NL2uK638ALuMMu8AO1C:bwi00dm)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @JohnThomson)

___
*[`src/components/Footer.tsx` line 13 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/488#-NL1zVmqAmZWP7KgHmWT:-NL2QeBv2hBhqFBWRwAk:brevmdt) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/b96b0616d54a609f9a17e7ff7227b75d27706237/src/components/Footer.tsx#L13)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Will it need to change at a different width if it is being viewed in another language? (Or maybe we will just live with letting some buttons wrap their text in that case?)
</blockquote></details>

I've added code to try to set this value in a reasonable fashion.
___
*[`src/components/Footer.tsx` line 72 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/488#-NL21Jup1bGowlV2uBE2:-NL2RGeQ02-OoEFk9Ztk:bxirwa) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/b96b0616d54a609f9a17e7ff7227b75d27706237/src/components/Footer.tsx#L72)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This is being pushed into the (increased) top margin of the parent row, so positioning it using bottom: seems risky. What if some of the other items in the row need to wrap and therefore get bigger?
</blockquote></details>

overflow-x is set to hidden for the footer as a whole, so my understanding is that these items shouldn't wrap.
___
*[`src/components/Footer.tsx` line 142 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/488#-NL1zKgDC98_LEyeaHUo:-NL2tj4hAwSw4oEQubpy:bu36b12) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/b96b0616d54a609f9a17e7ff7227b75d27706237/src/components/Footer.tsx#L142)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Unless it's inherited from somewhere, I don't see that this has bold text like the card says it should.
</blockquote></details>

I added font-weight: bold;
___
*[`src/components/Footer.tsx` line 196 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/488#-NL2-1WyDIi4MNKF-r3k:-NL3TWX4BYWPDLHz0Cul:bjk0g4v) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/b96b0616d54a609f9a17e7ff7227b75d27706237/src/components/Footer.tsx#L196)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

There's a lot more room, typically, on the last row...do you think it should really switch at the same max-width? John's mockup does seem to show the Github button moving when it doesn't really need to, so that might be right...I would have been inclined not to move it until it independently needs to. On small screens the less space the footer takes up the better! This might be something to ask JohnH.
</blockquote></details>

I've separated the max-width values for the Donate button placement and the github button placement.

**Review by StephenMcConnel — COMMENTED** [review]
The new code handles fairly long Donate translation strings, but not ones that require two lines.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/488#-:-NL3TmdF4FF0Mno6bTIb:b-rbt1t)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @JohnThomson)

**Review by JohnThomson — APPROVED** [review]
I think you can right-align the contentful icon just by making the anchor that contains it lose its margin-right when the github icon moves.

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/488#-:-NL6gush42E-GjwnSBo1:b-b52rwl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Review by JohnThomson — APPROVED** [review]
I've approved it but will let you decide whether to have another go at aligning the icon before merging.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/488#-:-NL6r0Fy09ZSB_jRcTfc:b-rvuig8)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
