### PR TITLE
Add Columns (and Column) component for About page (BL-9381)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/261)

### CODE REVIEW

**Review by hatton — COMMENTED** [review]
Let me get this code and play with this... I don't understand at the moment the need for left vs. right, twocolumn, etc.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/261#-:-MQwcyTV-RwsQ9LKTGKp:btdtnit)* status: 0 of 4 files reviewed, all discussions resolved

**Review by hatton — CHANGES_REQUESTED** [review]
Ah, OK  we don't want to be using the `ContentfulMultipartPage` component at all, but  I see you just renamed something there because it was stepping on you `Column` component. All good.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/261#-:-MQweQtK3eDU_8fijsfg:bnqeryi)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[src/index.css, line 202 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/261#-MQwfMNe8YcMqsfYyDyT:-MQwfMNe8YcMqsfYyDyU:bt2ie9c) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/3fba7c66eaa4939338a405dd9e999beee8eacabc/src/index.css#L202)):*
> ```CSS
>     width: 50px;
> }
> .attribution-text {
> ```

Unless there is a special reason, all blorg styling nowadays is done via `emotion` (the `css={css ' blah blah ' }` you see around.

**Review by hatton — COMMENTED** [review]
So just the css thing, thanks.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/261#-:-MQwgIoRDLM15E_ZKvzM:b-2xldvg)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/261)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[src/index.css, line 202 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/261#-MQwfMNe8YcMqsfYyDyT:-MQxNsRn1ZYCMYqHngdJ:b-ju3ay8) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/3fba7c66eaa4939338a405dd9e999beee8eacabc/src/index.css#L202)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Unless there is a special reason, all blorg styling nowadays is done via `emotion` (the `css={css ' blah blah ' }` you see around.
</blockquote></details>

Done.  Also applied to the other new components I've added this week.

**Pull request merged**
