### PR TITLE
Put a line through disabled feature icons (tweak to BL-8131)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/214)

### CODE REVIEW

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/214)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Review by JohnThomson — COMMENTED** [review]
Don't merge yet! Breaks hover info on disabled icons

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/214#-:-MMS5p2t0JjT8nTRLq_d:b-az5qet)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Review by JohnThomson — COMMENTED** [review]
Fixed, OK to merge now.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/214#-:-MMS8WnS4V1yZTr5tQUo:b-4p5pb0)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @andrew-polk)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/214)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Comment by hatton** [comment]
Sorry, Alex agrees that we should not do this for now.

**Pull request closed without merging**
