### PR TITLE
BL-10968 Add location tables to stats

### PR DESCRIPTION
**Pull request by hatton**
Also some refactoring to remove duplicated code and code around sorting (comparing) number strings which doesn't seem to be needed because we already convert all number-strings to numbers before giving them to the grid.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/427)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/427)* status: all files reviewed, 5 unresolved discussions (waiting on @hatton)

___
*[package.json, line 37 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/427#-MwTUEr477M_XugAFGrv:-MwTUEr477M_XugAFGrw:b-7jrh4d) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/3f635c72b87014a42804f50cbfee1bc995b1862c/package.json#L37)):*
> ```JSON
>         "@nivo/bar": "^0.62.0",
>         "@sentry/browser": "^6.0.0",
>         "@types/lodash": "^4.14.178",
> ```

In the end it probably doesn't matter, but we've kept the @types dependencies in devDependencies to date.
___
*[src/components/statistics/CollectionStatsPage.tsx, line 99 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/427#-MwTUzYPDCU9ItErJzQW:-MwTUzYPDCU9ItErJzQX:b-t3o9ye) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/3f635c72b87014a42804f50cbfee1bc995b1862c/src/components/statistics/CollectionStatsPage.tsx#L99)):*
> ```XML
>             {
>                 label: l10n.formatMessage({
>                     id: "stats.locations",
> ```

Should this have a new entry in CodeStrings?



_Code quote:_
```XML
"stats.locations"
```
___
*[src/components/statistics/CollectionStatsPage.tsx, line 118 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/427#-MwTV6HW4eYqu2a5yVTh:-MwTV6HW4eYqu2a5yVTi:b-rhfsi9) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/3f635c72b87014a42804f50cbfee1bc995b1862c/src/components/statistics/CollectionStatsPage.tsx#L118)):*
> ```XML
>     }, [l10n]);
> 
>     const [currentScreenIndex, setCurrentScreenIndex] = useState(4); // TODO do not commit
> ```

// TODO do not commit

You were just testing me, right?



_Code quote:_
```XML
// TODO do not commit
```
___
*[src/components/statistics/GridWrapper.tsx, line 8 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/427#-MwTUZqT4Ocq-dHbmmMm:-MwTUZqT4Ocq-dHbmmMn:b3dsj0c) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/3f635c72b87014a42804f50cbfee1bc995b1862c/src/components/statistics/GridWrapper.tsx#L8)):*
> ```XML
> import React from "react";
> 
> export const StatsGridWrapper: React.FunctionComponent<{
> ```

Mismatch between the file name and component name
___
*[src/components/statistics/StatsLocationScreen.tsx, line 39 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/427#-MwTVxtp5vSwADB_eU-d:-MwTVxtp5vSwADB_eU-e:bupyl1i) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/3f635c72b87014a42804f50cbfee1bc995b1862c/src/components/statistics/StatsLocationScreen.tsx#L39)):*
> ```XML
>         { name: "region", title: "Region", l10nId: "region" },
>         { name: "city", title: "City", l10nId: "city" },
>         { name: "reads", title: "Reads", l10nId: "reads" },
> ```

I guess we are not internationalizing at this time?

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/427)* status: 4 of 10 files reviewed, 5 unresolved discussions (waiting on @andrew-polk)

___
*[package.json, line 37 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/427#-MwTUEr477M_XugAFGrv:-MwXdXl7BkmymFljYnzq:b-896fix) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/3f635c72b87014a42804f50cbfee1bc995b1862c/package.json#L37)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

In the end it probably doesn't matter, but we've kept the @types dependencies in devDependencies to date.
</blockquote></details>

Done.
___
*[src/components/statistics/CollectionStatsPage.tsx, line 99 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/427#-MwTUzYPDCU9ItErJzQW:-MwXdZOY8NsZFQQ1drJA:bnojlyn) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/3f635c72b87014a42804f50cbfee1bc995b1862c/src/components/statistics/CollectionStatsPage.tsx#L99)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Should this have a new entry in CodeStrings?
</blockquote></details>

Right, no localization yet in stats
___
*[src/components/statistics/CollectionStatsPage.tsx, line 118 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/427#-MwTV6HW4eYqu2a5yVTh:-MwXdbLX9_AC19gXHGVy:b-896fix) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/3f635c72b87014a42804f50cbfee1bc995b1862c/src/components/statistics/CollectionStatsPage.tsx#L118)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

// TODO do not commit

You were just testing me, right?
</blockquote></details>

Done.
___
*[src/components/statistics/StatsLocationScreen.tsx, line 39 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/427#-MwTVxtp5vSwADB_eU-d:-MwXdd-m8BrJ8kRy670T:bnojlyn) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/3f635c72b87014a42804f50cbfee1bc995b1862c/src/components/statistics/StatsLocationScreen.tsx#L39)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I guess we are not internationalizing at this time?
</blockquote></details>

Right, no localization yet in stats
___
*[src/components/statistics/GridWrapper.tsx, line 8 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/427#-MwTUZqT4Ocq-dHbmmMm:-MwXdcWV3TdPP8Xd8eN9:b-896fix) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/3f635c72b87014a42804f50cbfee1bc995b1862c/src/components/statistics/GridWrapper.tsx#L8)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Mismatch between the file name and component name
</blockquote></details>

Done.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/427)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[src/components/statistics/CollectionStatsPage.tsx, line 118 at r2](https://reviewable.io/reviews/bloombooks/bloomlibrary2/427#-MwXjlENDm5Vh5ozHtBC:-MwXjlENDm5Vh5ozHtBD:bqr76oj) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/d7996cc6bb04752125eb8a180df070b8eb9c4d0a/src/components/statistics/CollectionStatsPage.tsx#L118)):*
> ```XML
>     }, [l10n]);
> 
>     const [currentScreenIndex, setCurrentScreenIndex] = useState(1);
> ```

Doesn't this mean that the Overview will not be the initial one loaded? Is that intentional?



_Code quote:_
```XML
useState(1)
```

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/427)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/components/statistics/CollectionStatsPage.tsx, line 118 at r2](https://reviewable.io/reviews/bloombooks/bloomlibrary2/427#-MwXjlENDm5Vh5ozHtBC:-MwYLcHw0-V-RGGjSyw5:b-896fix) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/d7996cc6bb04752125eb8a180df070b8eb9c4d0a/src/components/statistics/CollectionStatsPage.tsx#L118)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Doesn't this mean that the Overview will not be the initial one loaded? Is that intentional?
</blockquote></details>

Done.

**Pull request merged**
