### PR TITLE
Fix swiper width when in a flex column

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/271)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Wait a bit on this...may have better idea.

**Comment by JohnThomson** [comment]
OK, good to go now

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/271)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/components/CardSwiper.tsx, line 8 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/271#-MR6rSj86hctbJ28Ulx5:-MR6rSj86hctbJ28Ulx6:b-m8kat) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/b21668021433e3038201228ffb1e88eacba17fa9/src/components/CardSwiper.tsx#L8)):*
> ```XML
> import "swiper/components/a11y/a11y.min.css";
> import { useResponsiveChoice } from "../responsiveUtilities";
> import { number } from "@storybook/addon-knobs";
> ```

errant import (from storybook)

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/271)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/components/CardSwiper.tsx, line 8 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/271#-MR6rSj86hctbJ28Ulx5:-MR6tfCN3dtwUNJsbNEw:b-egcigf) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/b21668021433e3038201228ffb1e88eacba17fa9/src/components/CardSwiper.tsx#L8)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

errant import (from storybook)
</blockquote></details>

Grrrr. Silly me. Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/271)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
