### PR TITLE
Add new tags to tag list immediately (BL-9241)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/216)

### CODE REVIEW

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/216)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/components/Admin/StaffMultiChoosers.tsx, line 139 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/216#-MMSfPH7EtQCfb77YTxg:-MMSfPH7EtQCfb77YTxh:ba01450) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/9663d9e682d91ed79415c78477b24263bb6e2d72/src/components/Admin/StaffMultiChoosers.tsx#L139)):*
> ```XML
> 
>                     return result;
>                 });
> ```

This makes it available in this instance of the TagsChooser, but I don't know what that scope or lifetime is... do you? E.g. if you go off and do other things and come back to a new book, is it the same TagsChooser?

If so, that leave the chooser in the grid out, which might be part of the normal workflow.

Would it make sense to to push it into the CachedTablesContext / CachedTables (I don't know the difference)?

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/216)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/components/Admin/StaffMultiChoosers.tsx, line 139 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/216#-MMSfPH7EtQCfb77YTxg:-MMSgFuh2scSQSVWgRJB:b-7elhjv) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/9663d9e682d91ed79415c78477b24263bb6e2d72/src/components/Admin/StaffMultiChoosers.tsx#L139)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

This makes it available in this instance of the TagsChooser, but I don't know what that scope or lifetime is... do you? E.g. if you go off and do other things and come back to a new book, is it the same TagsChooser?

If so, that leave the chooser in the grid out, which might be part of the normal workflow.

Would it make sense to to push it into the CachedTablesContext / CachedTables (I don't know the difference)? 


</blockquote></details>

I guess I can't edit my comment, so let me clarify the second paragraph:

Even if that is not a problem, we still have the problem the chooser in the grid out. Using that in the same session might be part of the normal workflow.

**Comment by andrew-polk** [comment]
___
*[src/components/Admin/StaffMultiChoosers.tsx, line 139 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/216#-MMSfPH7EtQCfb77YTxg:-MMSix4a1FU__cSYiJ_g:b-t3z3s9) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/9663d9e682d91ed79415c78477b24263bb6e2d72/src/components/Admin/StaffMultiChoosers.tsx#L139)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I guess I can't edit my comment, so let me clarify the second paragraph:

Even if that is not a problem, we still have the problem the chooser in the grid out. Using that in the same session might be part of the normal workflow.
</blockquote></details>

This is directly modifying the array which is available via CachedTablesContext.
I just tested it, and it does show up in the grid.
I had previously tested from book to book.

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/216)* status: 0 of 1 files reviewed, all discussions resolved

___
*[src/components/Admin/StaffMultiChoosers.tsx, line 139 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/216#-MMSfPH7EtQCfb77YTxg:-MMSlusP1oxHz8AfcqbO:b8b58ly) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/9663d9e682d91ed79415c78477b24263bb6e2d72/src/components/Admin/StaffMultiChoosers.tsx#L139)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This is directly modifying the array which is available via CachedTablesContext.
I just tested it, and it does show up in the grid.
I had previously tested from book to book.
</blockquote></details>

OK cool. Since thatsan artifact that was a happy surprise to me (the evils of mutable return values), let's add a comment explaining that. THx

**Comment by andrew-polk** [comment]
___
*[src/components/Admin/StaffMultiChoosers.tsx, line 139 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/216#-MMSfPH7EtQCfb77YTxg:-MMSjFPcBayrpcgiINz7:b-896fix) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/9663d9e682d91ed79415c78477b24263bb6e2d72/src/components/Admin/StaffMultiChoosers.tsx#L139)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

OK cool. Since thatsan artifact that was a happy surprise to me (the evils of mutable return values), let's add a comment explaining that. THx
</blockquote></details>

Done.

**Pull request merged**
