### PR TITLE
Prevent getLocales from being a performance bottleneck

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/257)

### CODE REVIEW

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/257)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[src/connection/UseContentful.tsx, line 44 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/257#-MQb5bDV2k6EhB-s8ejb:-MQb5bDWCdYK6wcPCe3j:b-fwxb0) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/eb430ca6362dea7196e58afb885a5f2210e2f309/src/connection/UseContentful.tsx#L44)):*
> ```XML
>             // This is just a safety net.
>             // Without this, if the hardcoded locale list in useGetContentfulLocales
>             // has a locale which isn't set up in Contentful, we would get an error.
> ```

I find this comment confusing, because if I'm reading the code here right, what it does is make sure we
DO get an immediate error report if we ask for a non-existent locale. The point is that without it
we would get a confusing error elsewhere trying to use the nonexistent data in the nonexistent locale.
Should we have a fall-back? What if we have SOME data in French, so it's in the list, but not everything has been translated?
___
*[src/connection/UseContentful.tsx, line 61 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/257#-MQb67H50KkpT78oouea:-MQb67H50KkpT78ooueb:b3s8tus) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/eb430ca6362dea7196e58afb885a5f2210e2f309/src/connection/UseContentful.tsx#L61)):*
> ```XML
>                     locale: localeForEntries,
>                     ...query,
>                     limit: 1000, // without this, we would only get 100 collections
> ```

We aren't necessarily retrieving collections here, are we?
Also: does contentful really have this same limit? Or did we somehow carry this over from parse server?

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/257)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[src/connection/UseContentful.tsx, line 44 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/257#-MQb5bDV2k6EhB-s8ejb:-MQlw2QjEcvDvalx0sBi:ba3qa83) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/eb430ca6362dea7196e58afb885a5f2210e2f309/src/connection/UseContentful.tsx#L44)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I find this comment confusing, because if I'm reading the code here right, what it does is make sure we
DO get an immediate error report if we ask for a non-existent locale. The point is that without it
we would get a confusing error elsewhere trying to use the nonexistent data in the nonexistent locale.
Should we have a fall-back? What if we have SOME data in French, so it's in the list, but not everything has been translated?
</blockquote></details>

Errors only occur if we request resources for a locale which is not set up in contentful at all (at the top level). If a specific resource doesn't have a value for that locale, it automatically falls back in contentful.

So all this does is makes sure that if we ever remove a locale from the top-level setup in contentful, it won't make the site unusable for anyone trying to view it for that locale.
___
*[src/connection/UseContentful.tsx, line 61 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/257#-MQb67H50KkpT78oouea:-MQlvkqh1YOswaiLgRrY:b-w9ifjf) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/eb430ca6362dea7196e58afb885a5f2210e2f309/src/connection/UseContentful.tsx#L61)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

We aren't necessarily retrieving collections here, are we?
Also: does contentful really have this same limit? Or did we somehow carry this over from parse server?
</blockquote></details>

No, not necessarily collections. But that is the one which will hit the limit. But I will clarify the comment.

Nothing to do with parse. The default limit from contentful's API is 100.

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/257)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[src/connection/UseContentful.tsx, line 61 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/257#-MQb67H50KkpT78oouea:-MQlxe9n6D-7LpdwHQSB:b-896fix) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/eb430ca6362dea7196e58afb885a5f2210e2f309/src/connection/UseContentful.tsx#L61)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

No, not necessarily collections. But that is the one which will hit the limit. But I will clarify the comment.

Nothing to do with parse. The default limit from contentful's API is 100.

</blockquote></details>

Done.

**Review by JohnThomson — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/257)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @JohnThomson)

___
*[src/connection/UseContentful.tsx, line 44 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/257#-MQb5bDV2k6EhB-s8ejb:-MQmGeF8-vCbrJ5-HYfH:b-jzcmm2) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/eb430ca6362dea7196e58afb885a5f2210e2f309/src/connection/UseContentful.tsx#L44)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Errors only occur if we request resources for a locale which is not set up in contentful at all (at the top level). If a specific resource doesn't have a value for that locale, it automatically falls back in contentful.

So all this does is makes sure that if we ever remove a locale from the top-level setup in contentful, it won't make the site unusable for anyone trying to view it for that locale.
</blockquote></details>

So, removing a locale from contentful and failing to remove it from the hard-coded list would be a mistake on our part, right? I would think we'd want that to fail fast so we fix it. But you're saying this code...which looks as though it's intended to make sure and error gets properly thrown rather than ignored...is actually intended to prevent that sort of fail-fast error? Can we capture some more of this in the comment?

**Review by JohnThomson — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/257)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @andrew-polk)

**Pull request merged**
