### PR TITLE
BL-9697 Fix publisher/originalPublisher searches

### PR DESCRIPTION
**Pull request by gmartin7**
* 2 commits - first is fixing various warnings, second is the actual fix

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/317)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/317)* status: all files reviewed, 3 unresolved discussions (waiting on @gmartin7)

___
*[src/connection/LibraryQueryHooks.ts, line 828 at r2](https://reviewable.io/reviews/bloombooks/bloomlibrary2/317#-MWBdeu7B5_aNyqAvYq3:-MWBdeu7B5_aNyqAvYq4:bjsr0sc) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/2e4a940b3402a1a2c492f3e5b40fa0babd20c269/src/connection/LibraryQueryHooks.ts#L828)):*
> ```XML
>                 end = index + part.length;
>                 if (part.indexOf(" ") > -1) {
>                     end = end + 2; // account for quotes we removed
> ```

Is the logic correct if we have quotes with no space between them?
Does it simplify things to have the function return part and end? (It may well not.)
___
*[src/connection/SplitString.test.ts, line 132 at r2](https://reviewable.io/reviews/bloombooks/bloomlibrary2/317#-MWBcidbEwX8jWRFkMUv:-MWBcidcBQnChqtCo4w9:bagprby) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/2e4a940b3402a1a2c492f3e5b40fa0babd20c269/src/connection/SplitString.test.ts#L132)):*
> ```
>     expect(specialParts[0]).toBe("originalPublisher:Bob");
>     expect(specialParts[1]).toBe("publisher:Pratham");
> ```
So would this be better as 
> ```
>     expect(specialParts.includes("originalPublisher:Bob");
>     expect(specialParts.includes("publisher:Pratham");
> ```
?
And similar below?
Then you can remove the comment about order because we actually don't care.
___
*[src/connection/SplitString.test.ts, line 157 at r2](https://reviewable.io/reviews/bloombooks/bloomlibrary2/317#-MWBdIMl8lxWmdljCQb1:-MWBdIMl8lxWmdljCQb2:b-v01xun) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/2e4a940b3402a1a2c492f3e5b40fa0babd20c269/src/connection/SplitString.test.ts#L157)):*
> ```XML
>     expect(specialParts.length).toBe(1);
>     expect(specialParts[0]).toBe("publisher:");
> });
> ```

I see some cases which may be missing:
`facet: value` (space after colon but no quotes) ...but maybe that is in an existing test?
`facet:"nospace"`
`facet: "where is my trailing quote`
`facet: where is my leading quote"`
`facet: "i seem to have" "three`
`"quote but no facet"` ...maybe handled in existing test?

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/317)* status: all files reviewed, 3 unresolved discussions (waiting on @gmartin7)

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/317)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[src/connection/LibraryQueryHooks.ts, line 828 at r2](https://reviewable.io/reviews/bloombooks/bloomlibrary2/317#-MWBdeu7B5_aNyqAvYq3:-MWPmIX88ELAD_z1rGzm:b-uys3gw) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/2e4a940b3402a1a2c492f3e5b40fa0babd20c269/src/connection/LibraryQueryHooks.ts#L828)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is the logic correct if we have quotes with no space between them?
Does it simplify things to have the function return part and end? (It may well not.)
</blockquote></details>

Current code test failed with `publisher: ""`. Test added. Fixed.
___
*[src/connection/SplitString.test.ts, line 132 at r2](https://reviewable.io/reviews/bloombooks/bloomlibrary2/317#-MWBcidbEwX8jWRFkMUv:-MWPeqvW1qed6RYLnWFI:bw4dgt0) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/2e4a940b3402a1a2c492f3e5b40fa0babd20c269/src/connection/SplitString.test.ts#L132)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
>     expect(specialParts[0]).toBe("originalPublisher:Bob");
>     expect(specialParts[1]).toBe("publisher:Pratham");
> ```
So would this be better as 
> ```
>     expect(specialParts.includes("originalPublisher:Bob");
>     expect(specialParts.includes("publisher:Pratham");
> ```
?
And similar below?
Then you can remove the comment about order because we actually don't care.
</blockquote></details>

Done. And for most of the other tests in this file too.
___
*[src/connection/SplitString.test.ts, line 157 at r2](https://reviewable.io/reviews/bloombooks/bloomlibrary2/317#-MWBdIMl8lxWmdljCQb1:-MWPjcLO0GZoGZVveNZ0:b-tg7j35) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/2e4a940b3402a1a2c492f3e5b40fa0babd20c269/src/connection/SplitString.test.ts#L157)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I see some cases which may be missing:
`facet: value` (space after colon but no quotes) ...but maybe that is in an existing test?
`facet:"nospace"`
`facet: "where is my trailing quote`
`facet: where is my leading quote"`
`facet: "i seem to have" "three`
`"quote but no facet"` ...maybe handled in existing test?
</blockquote></details>

The last one was covered in earlier tests. I've added tests for the others. Interestingly, the only one it had a problem with was the 2nd with quotes, but no space. Fixed.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/317)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Pull request merged**
