### PR TITLE
BL-9073 About page tweaks

### PR DESCRIPTION
**Pull request by gmartin7**
* change color bands
* center h1 headers

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/197)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/197)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[src/index.css, line 110 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/197#-MLTzApv4SGb_BN1SeGk:-MLTzApv4SGb_BN1SeGl:b-rhhqi2) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/eef04adecfe653f769032bfe686a8a2a1f9fbdc3/src/index.css#L110)):*
> ```CSS
> .base-contentful-page h1 {
>     font-size: 2rem;
>     text-align: center;
> ```

Doesn't seem like we want to center h1 for every page.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/197)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/index.css, line 110 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/197#-MLTzApv4SGb_BN1SeGk:-MLU3WdU-m6pq2YErT4P:b-yk9tby) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/eef04adecfe653f769032bfe686a8a2a1f9fbdc3/src/index.css#L110)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Doesn't seem like we want to center h1 for every page.
</blockquote></details>

Done. Made it just the About page

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/197)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by andrew-polk — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/197)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
