### PR TITLE
BL-9073 More About page changes

### PR DESCRIPTION
**Pull request by gmartin7**
* add colored bands alternating per section
* make secondary markdown float to right
* update several sections to be more like original
   About page

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/191)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/191)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[src/components/ContentfulMarkdownPart.tsx, line 14 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/191#-MLFM_Pi61tQKTdhpc2S:-MLFM_Pj6e3GHLl3cmbE:b-jkp3en) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/29b61dbb277015b6f8e3bc6642bf36105f846d84/src/components/ContentfulMarkdownPart.tsx#L14)):*
> ```XML
> export const ContentfulMarkdownPart: React.FunctionComponent<{
>     markdown: string;
>     flexValue: number;
> ```

I think it would be better to call this something more semantically helpful. Like columnNumber? Or maybe we need an enum to make it more understandable?
Also, it seems like it would better if it was optional and set to the value used by ContentfulPage if not provided.

Then lets put some helpful comments on the prop and the values set based on its value (justification, etc.)

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/191)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/components/ContentfulMarkdownPart.tsx, line 14 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/191#-MLFM_Pi61tQKTdhpc2S:-MLKF6nuAc9_0Kg2slEF:b-896fix) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/29b61dbb277015b6f8e3bc6642bf36105f846d84/src/components/ContentfulMarkdownPart.tsx#L14)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think it would be better to call this something more semantically helpful. Like columnNumber? Or maybe we need an enum to make it more understandable?
Also, it seems like it would better if it was optional and set to the value used by ContentfulPage if not provided.

Then lets put some helpful comments on the prop and the values set based on its value (justification, etc.)
</blockquote></details>

Done.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/191)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/191)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
