### PR TITLE
Remove duplicate headings/counts from RISE-PNG (BL-10859)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/415)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/415)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[src/components/BookCardGroup.tsx, line 344 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/415#-Mv-3e9I2SVrZqBOpUFR:-Mv-3e9I2SVrZqBOpUFS:b-f8l00m) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/055db4365068c67851924ead5cf64b3fd8b81095/src/components/BookCardGroup.tsx#L344)):*
> ```XML
>         group = (
>             <React.Fragment>
>                 {props.hideHeaderAndCount || responsiveHeaderAndCount}
> ```

Won't this still leave the cards indented when they shouldn't be?

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/415)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/components/BookCardGroup.tsx, line 344 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/415#-Mv-3e9I2SVrZqBOpUFR:-Mv-WqPd16xyKmLzGEAD:b6rlppd) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/055db4365068c67851924ead5cf64b3fd8b81095/src/components/BookCardGroup.tsx#L344)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Won't this still leave the cards indented when they shouldn't be?
</blockquote></details>

I've now removed the wrapping element that caused the indentation.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/415)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/components/BookCardGroup.tsx, line 344 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/415#-Mv-3e9I2SVrZqBOpUFR:-Mv-koLqCVdXFTSqrYsa:b-ybfgmb) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/055db4365068c67851924ead5cf64b3fd8b81095/src/components/BookCardGroup.tsx#L344)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

The indentation and header need to be there in some circumstances.
Look at https://alpha.bloomlibrary.org/bible/GRN-Look-Listen-Live, for example.
And the relevant card https://issues.bloomlibrary.org/youtrack/issue/BL-10722.
</blockquote></details>

OK, I've complicated things so that both GRN-Look-Listen-Live and rise-png both work properly.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/415)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
