### PR TITLE
More performance improvements

### PR DESCRIPTION
**Pull request by JohnThomson**
Code splits for stats and firebase

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/262)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/262)* status: all files reviewed, 5 unresolved discussions (waiting on @JohnThomson)

___
*[src/Utilities.ts, line 47 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/262#-MQxWB037QbufDY7InJf:-MQxWB037QbufDY7InJg:b-i7yedu) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/601f66979418ce54d09c8b6346278a128907cb2d/src/Utilities.ts#L47)):*
> ```XML
>     }
>     return "";
> }
> ```

Probably this came from an SO article or something, but I would like to see more meaningful variable names.
And go ahead and make exdays above more explicit, please.
___
*[src/components/statistics/CollectionStatsPageCodeSplit.tsx, line 7 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/262#-MQxWX3913wOS8u5hH_m:-MQxWX3913wOS8u5hH_n:b-w56tyx) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/601f66979418ce54d09c8b6346278a128907cb2d/src/components/statistics/CollectionStatsPageCodeSplit.tsx#L7)):*
> ```
> BookDetail
> ```
CollectionStatsPage
___
*[src/firebase/StyledFirebaseAuthCodeSplit.tsx, line 6 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/262#-MQxXFwlDjugLWu-QTFK:-MQxXFwlDjugLWu-QTFL:b3wlcxt) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/601f66979418ce54d09c8b6346278a128907cb2d/src/firebase/StyledFirebaseAuthCodeSplit.tsx#L6)):*
> ```
> export interface ICollectionStatsPageProps {
>     collectionName: string;
> }
> ```
I think this can be removed?
___
*[src/firebase/StyledFirebaseAuthCodeSplit.tsx, line 94 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/262#-MQxXaqT8XgIZCJupF9l:-MQxXaqT8XgIZCJupF9m:bx93k4k) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/601f66979418ce54d09c8b6346278a128907cb2d/src/firebase/StyledFirebaseAuthCodeSplit.tsx#L94)):*
> ```
> Loading Bulk Edit...
> ```
How about Loading login screen...?
___
*[src/firebase/StyledFirebaseAuthCodeSplit.tsx, line 116 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/262#-MQxXktL-gApHFuitcWJ:-MQxXktL-gApHFuitcWK:b6gplyh) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/601f66979418ce54d09c8b6346278a128907cb2d/src/firebase/StyledFirebaseAuthCodeSplit.tsx#L116)):*
> ```XML
> //     });
> 
> // };
> ```

Extraneous comments

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/262)* status: all files reviewed, 5 unresolved discussions (waiting on @andrew-polk)

___
*[src/Utilities.ts, line 47 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/262#-MQxWB037QbufDY7InJf:-MQxpIYm1dyx5qAP9V5W:b-896fix) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/601f66979418ce54d09c8b6346278a128907cb2d/src/Utilities.ts#L47)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Probably this came from an SO article or something, but I would like to see more meaningful variable names.
And go ahead and make exdays above more explicit, please.
</blockquote></details>

Done.
___
*[src/components/statistics/CollectionStatsPageCodeSplit.tsx, line 7 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/262#-MQxWX3913wOS8u5hH_m:-MQxp0Oe4Z84HWuTmF9Z:b-896fix) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/601f66979418ce54d09c8b6346278a128907cb2d/src/components/statistics/CollectionStatsPageCodeSplit.tsx#L7)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> BookDetail
> ```
CollectionStatsPage
</blockquote></details>

Done.
___
*[src/firebase/StyledFirebaseAuthCodeSplit.tsx, line 6 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/262#-MQxXFwlDjugLWu-QTFK:-MQxpTgA9182YTriIogN:b-896fix) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/601f66979418ce54d09c8b6346278a128907cb2d/src/firebase/StyledFirebaseAuthCodeSplit.tsx#L6)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> export interface ICollectionStatsPageProps {
>     collectionName: string;
> }
> ```
I think this can be removed?
</blockquote></details>

Done.
___
*[src/firebase/StyledFirebaseAuthCodeSplit.tsx, line 94 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/262#-MQxXaqT8XgIZCJupF9l:-MQxpdqI3lr6sf5g9xLl:b-896fix) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/601f66979418ce54d09c8b6346278a128907cb2d/src/firebase/StyledFirebaseAuthCodeSplit.tsx#L94)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> Loading Bulk Edit...
> ```
How about Loading login screen...?
</blockquote></details>

Done.
___
*[src/firebase/StyledFirebaseAuthCodeSplit.tsx, line 116 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/262#-MQxXktL-gApHFuitcWJ:-MQxpf8VAqpi1chtpRHH:b-896fix) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/601f66979418ce54d09c8b6346278a128907cb2d/src/firebase/StyledFirebaseAuthCodeSplit.tsx#L116)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Extraneous comments
</blockquote></details>

Done.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/262)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/Utilities.ts, line 47 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/262#-MQxWB037QbufDY7InJf:-MQxqa345fpoSfDW3Kwg:b-cnlnyh) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/601f66979418ce54d09c8b6346278a128907cb2d/src/Utilities.ts#L47)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks. I was also hoping for a helpful name for `ca` and `c`.
And I see now that you have `var`s instead of `const` and `let`.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/262)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/Utilities.ts, line 47 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/262#-MQxWB037QbufDY7InJf:-MQxuU4O5Qm38x6z7AUd:bm9z2e7) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/601f66979418ce54d09c8b6346278a128907cb2d/src/Utilities.ts#L47)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Thanks. I was also hoping for a helpful name for `ca` and `c`.
And I see now that you have `var`s instead of `const` and `let`.
</blockquote></details>

I think I fixed them now

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/262)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
