### PR TITLE
Sync up grid export with grid (BL-14047)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/575)

### CODE REVIEW

**Review by JohnThomson — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/575)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`src/components/Grid/GridExport.ts` line 35 at r1](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/575#-OAdIMG44NYCQEKoy-c_:-OAdIMG44NYCQEKoy-ca:bhdzlly) ([raw file](https://github.com/BloomBooks/BloomLibrary2/blob/10d5434bcf283ce4ce0e3d64050c1e4ae2de93c5/src/components/Grid/GridExport.ts#L35)):*
> ```XML
>     },
>     new Map<string, IGridColumn>()
> );
> ```

This will work, but it doesn't feel like a job for reduce. Nothing is being accumulated. Why not just
const static_keyToColumnDefinition = new Map<...>;
getBookGrid...().forEach(cd => staticKeyToColumnDefinition.set(cd.name, cd);
___
*[`src/components/Grid/GridExport.ts` line 134 at r1](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/575#-OAdKdcU6tBZX-rJ0bhC:-OAdKdcU6tBZX-rJ0bhD:bcug65h) ([raw file](https://github.com/BloomBooks/BloomLibrary2/blob/10d5434bcf283ce4ce0e3d64050c1e4ae2de93c5/src/components/Grid/GridExport.ts#L134)):*
> ```XML
>                 : "false";
>         case "Is Rebrand":
>             return book.rebrand ? "true" : "false";
> ```

I suppose the deleted ones already have getCellValue() functions set in the columnDefinitions? While the remaining ones have a getCellValue that doesn't return a string?
Could we add to ColumnDefinition a GetStringCellValue function so we can clean out all the special cases here and have the knowledge about how to get a cell value from a book and key all in one place?
Maybe a base class so that a default version of GetStringCellValue calls getCellValue() and throws if the result is not a string?

**Comment by andrew-polk** [comment]
*[`src/components/Grid/GridExport.ts` line 134 at r1](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/575#-OAdKdcU6tBZX-rJ0bhC:-OAdlsAWBP0r_40uxbpp:b-vi6qrj) ([raw file](https://github.com/BloomBooks/BloomLibrary2/blob/10d5434bcf283ce4ce0e3d64050c1e4ae2de93c5/src/components/Grid/GridExport.ts#L134)):*
> I suppose the deleted ones already have getCellValue() functions set in the columnDefinitions? While the remaining ones have a getCellValue that doesn't return a string?

correct

> Could we add to ColumnDefinition a GetStringCellValue function so we can clean out all the special cases here and have the knowledge about how to get a cell value from a book and key all in one place?  
Maybe a base class so that a default version of GetStringCellValue calls getCellValue() and throws if the result is not a string?

Yeah, I had struggled with the best way to do this.
I like your idea. 
But I don't want to complicate things with a class. For one thing, we almost don't use classes at all in this code. For another, the current interface is actually an extension of an interface we don't control (which contains getCellValue), so it seemed like that was going to get really messy quickly.

See what you think of what I've done. I think it is an improvement, anyway.

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/575)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[`src/components/Grid/GridExport.ts` line 35 at r1](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/575#-OAdIMG44NYCQEKoy-c_:-OAddre544-lRRHIdK66:b-at8158) ([raw file](https://github.com/BloomBooks/BloomLibrary2/blob/10d5434bcf283ce4ce0e3d64050c1e4ae2de93c5/src/components/Grid/GridExport.ts#L35)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This will work, but it doesn't feel like a job for reduce. Nothing is being accumulated. Why not just
const static_keyToColumnDefinition = new Map<...>;
getBookGrid...().forEach(cd => staticKeyToColumnDefinition.set(cd.name, cd);
</blockquote></details>

Good point. Much more readable, too.
I admit this was a case of letting copilot program...

**Review by JohnThomson — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/575)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @andrew-polk)

___
*[`src/components/Grid/GridExport.ts` line 134 at r1](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/575#-OAdKdcU6tBZX-rJ0bhC:-OAdp4XYA_NCkzI2-1BI:bdjmjn9) ([raw file](https://github.com/BloomBooks/BloomLibrary2/blob/10d5434bcf283ce4ce0e3d64050c1e4ae2de93c5/src/components/Grid/GridExport.ts#L134)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> I suppose the deleted ones already have getCellValue() functions set in the columnDefinitions? While the remaining ones have a getCellValue that doesn't return a string?

correct

> Could we add to ColumnDefinition a GetStringCellValue function so we can clean out all the special cases here and have the knowledge about how to get a cell value from a book and key all in one place?  
Maybe a base class so that a default version of GetStringCellValue calls getCellValue() and throws if the result is not a string?

Yeah, I had struggled with the best way to do this.
I like your idea. 
But I don't want to complicate things with a class. For one thing, we almost don't use classes at all in this code. For another, the current interface is actually an extension of an interface we don't control (which contains getCellValue), so it seemed like that was going to get really messy quickly.

See what you think of what I've done. I think it is an improvement, anyway.
</blockquote></details>

Looks fine to me. Much simpler than introducing objects, actually.

**Pull request merged**
