### PR TITLE
Don't show language cards with no books (BL-10796)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/388)

### CODE REVIEW

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/388)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @andrew-polk and @JohnThomson)

___
*[src/components/LanguageGroup.tsx, line 51 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/388#-Mr3yyD98T7mz_besznC:-Mr3yyD98T7mz_besznD:b-l220nl) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/504be720c00710813684eadb57c4cf204925ebf6/src/components/LanguageGroup.tsx#L51)):*
> ```XML
>         getMenuProps: (options: GetMenuPropsOptions) => {}
>     ) => {
>         filteredLanguages = getLanguagesFilteredBySearchTerm(filter).filter(
> ```

I don't like the double use of filter here.  How about we rename the param 'searchTerm'? And then maybe we could improve the method name, too. Something like GetCardsForLanguagesMatchingSearchTermThatHaveBooks? Or if that's too long, maybe GetCardsForInterestingLanguages?

**Review by JohnThomson — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/388)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/388)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/components/LanguageGroup.tsx, line 51 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/388#-Mr3yyD98T7mz_besznC:-Mr41A8o52mV70RViodR:bn9tkq4) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/504be720c00710813684eadb57c4cf204925ebf6/src/components/LanguageGroup.tsx#L51)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I don't like the double use of filter here.  How about we rename the param 'searchTerm'? And then maybe we could improve the method name, too. Something like GetCardsForLanguagesMatchingSearchTermThatHaveBooks? Or if that's too long, maybe GetCardsForInterestingLanguages?
</blockquote></details>

Thanks. See what you think.

**Review by JohnThomson — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/388)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @andrew-polk)

**Pull request merged**
