### PR TITLE
BL-9252 localize Topics

### PR DESCRIPTION
**Pull request by gmartin7**
* get csv file with new topic ids and English (and Spanish)
   updated in the repo before uploading to Crowdin

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/213)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
I think we also need a change to Collections.makeTopicCollectionsForCards()

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/213#-:-MMRyhig9hb6DbSkRAOg:bm27991)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[src/model/useInternationalizedTopics.ts, line 22 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/213#-MMRyqch6xakj2VpYkJk:-MMRyqch6xakj2VpYkJl:bc89926) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/8ebdb9e569e459cd882b136ec3c36b170f72bc80/src/model/useInternationalizedTopics.ts#L22)):*
> ```XML
>         defaultMessage: "Other",
>     });
>     if (other) {
> ```

Maybe I'm missing something, but won't we always get `other`? 
That, in turn, I think, means we can simplify the use of this in ByTopicsGroups so we don't have to check if it exists.
And I think we can even make `intlzdTopic` required which simplifies other logic. (Personally, I would rename it to `localizedTopic`.)

**Comment by andrew-polk** [comment]
___
*[src/model/useInternationalizedTopics.ts, line 22 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/213#-MMRyqch6xakj2VpYkJk:-MMS1YxPEdJZ1lGwNvqk:b4rf51i) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/8ebdb9e569e459cd882b136ec3c36b170f72bc80/src/model/useInternationalizedTopics.ts#L22)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Maybe I'm missing something, but won't we always get `other`? 
That, in turn, I think, means we can simplify the use of this in ByTopicsGroups so we don't have to check if it exists.
And I think we can even make `intlzdTopic` required which simplifies other logic. (Personally, I would rename it to `localizedTopic`.)
</blockquote></details>

Or maybe even make it key and name or displayName.

Could even define ITopic { key:string; displayName:string;}

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/213)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/model/useInternationalizedTopics.ts, line 22 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/213#-MMRyqch6xakj2VpYkJk:-MMSOA3zBTDJLWyE0YU0:b-vc8t04) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/8ebdb9e569e459cd882b136ec3c36b170f72bc80/src/model/useInternationalizedTopics.ts#L22)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Or maybe even make it key and name or displayName.

Could even define ITopic { key:string; displayName:string;}
</blockquote></details>

`ITopic` defined. Thx.
I changed `makeCollectionForTopic()` take an `ITopic` which simplified some things. Unfortunately, `makeCollectionForTopic()` is also used in `CollectionSubsetPage.tsx` where we can't easily get a `localizedTopic`.

I had wanted to use my custom hook in `makeCollectionForTopic()`, but it isn't a React function component or hook itself, so I had to put it in ByTopicsGroups, which is a function component.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/213)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/model/useInternationalizedTopics.ts, line 22 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/213#-MMRyqch6xakj2VpYkJk:-MMSZLPxErXNK8Hu5Uwt:b-6wdfu4) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/8ebdb9e569e459cd882b136ec3c36b170f72bc80/src/model/useInternationalizedTopics.ts#L22)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

`ITopic` defined. Thx.
I changed `makeCollectionForTopic()` take an `ITopic` which simplified some things. Unfortunately, `makeCollectionForTopic()` is also used in `CollectionSubsetPage.tsx` where we can't easily get a `localizedTopic`.

I had wanted to use my custom hook in `makeCollectionForTopic()`, but it isn't a React function component or hook itself, so I had to put it in ByTopicsGroups, which is a function component.
</blockquote></details>

Grr... Reviewable isn't showing my latest on this file! Why not!?

**Comment by gmartin7** [comment]
Rebase errors. Closing this PR. Will open a new one.

**Pull request closed without merging**
