### PR TITLE
Add some missing internationalizations

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/231)

### CODE REVIEW

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/231)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @andrew-polk)

___
*[src/components/ByLevelGroups.tsx, line 41 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/231#-MNzig3aD4TqBVpG_qp8:-MNzig3aD4TqBVpG_qp9:b9vq0ua) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/076192cb285117b5ca655998c9b5b9033fad3ec4/src/components/ByLevelGroups.tsx#L41)):*
> ```XML
>                 title={l10n.formatMessage({
>                     id: "level.missing",
>                     defaultMessage: "Books for which we are missing levels",
> ```

I don' t know if it is possible to actually get in this situation... but since we're here... do you think the English would be better as "Books that don't have a level".?
___
*[src/components/ByLevelGroups.tsx, line 68 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/231#-MNzhlV39JhX-Wm4sJT2:-MNzhlV39JhX-Wm4sJT3:b-rt8o7x) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/076192cb285117b5ca655998c9b5b9033fad3ec4/src/components/ByLevelGroups.tsx#L68)):*
> ```XML
>         {
>             id: "level.collectionRowLabel",
>             defaultMessage: "{collectionName} - Level {levelNumber}",
> ```

I think translators will needs a description on these, and a screenshot linked, later (Colin can see to that)
___
*[src/components/ByLevelGroups.tsx, line 70 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/231#-MNziNgv7G3f3_xnR6VW:-MNziNgv7G3f3_xnR6VX:b-ebrhjc) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/076192cb285117b5ca655998c9b5b9033fad3ec4/src/components/ByLevelGroups.tsx#L70)):*
> ```XML
>             defaultMessage: "{collectionName} - Level {levelNumber}",
>         },
>         { collectionName: baseCollection.label, levelNumber: level }
> ```

Does baseCollection.label also need to be localized here?
___
*[src/components/ByLevelGroups.tsx, line 77 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/231#-MNzi0fl2ukaTR7jVFFq:-MNzi0fl2ukaTR7jVFFr:b-rt8o7x) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/076192cb285117b5ca655998c9b5b9033fad3ec4/src/components/ByLevelGroups.tsx#L77)):*
> ```XML
>             {
>                 id: "level.collectionRowLabel.missing",
>                 defaultMessage: "{collectionName} - (missing a level)",
> ```

I think translators will needs a description on these, and a screenshot linked, later (Colin can see to that)
___
*[src/components/ByLevelGroups.tsx, line 79 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/231#-MNziUJK9W6cYjBZUxdg:-MNziUJK9W6cYjBZUxdh:b-ebrhjc) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/076192cb285117b5ca655998c9b5b9033fad3ec4/src/components/ByLevelGroups.tsx#L79)):*
> ```XML
>                 defaultMessage: "{collectionName} - (missing a level)",
>             },
>             { collectionName: baseCollection.label }
> ```

Does baseCollection.label also need to be localized here?

**Review by hatton — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/231)* status: 0 of 5 files reviewed, 6 unresolved discussions (waiting on @andrew-polk)

___
*[src/components/ByLevelGroups.tsx, line 67 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/231#-MO1olpFD6SoxCuDgkZ_:-MO1olpFD6SoxCuDgkZa:b-sqwc48) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/076192cb285117b5ca655998c9b5b9033fad3ec4/src/components/ByLevelGroups.tsx#L67)):*
> ```XML
>     let label = l10n.formatMessage(
>         {
>             id: "level.collectionRowLabel",
> ```

I'm leaning towards instead composing this using the string you have already, "book.metadata.level".

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/231)* status: 0 of 13 files reviewed, 6 unresolved discussions (waiting on @hatton)

___
*[src/components/ByLevelGroups.tsx, line 41 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/231#-MNzig3aD4TqBVpG_qp8:-MO2Q1OT7tFsk2qw-xld:byvyago) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/076192cb285117b5ca655998c9b5b9033fad3ec4/src/components/ByLevelGroups.tsx#L41)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I don' t know if it is possible to actually get in this situation... but since we're here... do you think the English would be better as "Books that don't have a level".?
</blockquote></details>

Yes. Done.
___
*[src/components/ByLevelGroups.tsx, line 67 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/231#-MO1olpFD6SoxCuDgkZ_:-MO2qTQ99GHIUi0ZkNj1:b-896fix) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/076192cb285117b5ca655998c9b5b9033fad3ec4/src/components/ByLevelGroups.tsx#L67)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I'm leaning towards instead composing this using the string you have already, "book.metadata.level". 
</blockquote></details>

Done.
___
*[src/components/ByLevelGroups.tsx, line 68 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/231#-MNzhlV39JhX-Wm4sJT2:-MO2REcJ7LieC2y7h2jw:b-896fix) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/076192cb285117b5ca655998c9b5b9033fad3ec4/src/components/ByLevelGroups.tsx#L68)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I think translators will needs a description on these, and a screenshot linked, later (Colin can see to that)
</blockquote></details>

Done.
___
*[src/components/ByLevelGroups.tsx, line 70 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/231#-MNziNgv7G3f3_xnR6VW:-MO2NUB_8rcQQwsMK5hn:buypzsh) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/076192cb285117b5ca655998c9b5b9033fad3ec4/src/components/ByLevelGroups.tsx#L70)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Does baseCollection.label also need to be localized here?
</blockquote></details>

Yes. This led me to find other places, too.
___
*[src/components/ByLevelGroups.tsx, line 77 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/231#-MNzi0fl2ukaTR7jVFFq:-MO2RF5s4fb01e4P4tIn:b-896fix) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/076192cb285117b5ca655998c9b5b9033fad3ec4/src/components/ByLevelGroups.tsx#L77)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I think translators will needs a description on these, and a screenshot linked, later (Colin can see to that)
</blockquote></details>

Done.
___
*[src/components/ByLevelGroups.tsx, line 79 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/231#-MNziUJK9W6cYjBZUxdg:-MO2NTzz8-nlJOhYC5nW:b-896fix) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/076192cb285117b5ca655998c9b5b9033fad3ec4/src/components/ByLevelGroups.tsx#L79)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Does baseCollection.label also need to be localized here?
</blockquote></details>

Done.

**Review by hatton — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 8 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/231)* status: 9 of 13 files reviewed, 4 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[src/components/ByLevelGroups.tsx, line 77 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/231#-MNzi0fl2ukaTR7jVFFq:-MO3VsPO0CoSQ9E3Udl3:b-8o59ce) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/076192cb285117b5ca655998c9b5b9033fad3ec4/src/components/ByLevelGroups.tsx#L77)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Hmm... like the one above ( myCollection - level 3) this can be instead be got at by combining the translation of the collection name with "-" and then a simple "(missing level)" string. Or just "Missing Level". Would need a description giving an example of how it is used.  Note I've purposefully dropped the "a".
___
*[src/localization/Code Strings.json, line 80 at r2](https://reviewable.io/reviews/bloombooks/bloomlibrary2/231#-MO3cMlHE2b8cshi9fre:-MO3cMlHE2b8cshi9frf:b6i7gcx) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/13b9e8c6cf37b9ca5266d41c87dcf22346d5b859/src/localization/Code Strings.json#L80)):*
> ```JSON
>     "collectionRowLabel.missingLevel": {
>         "description": "Used to label books in a particular collection which are missing level information. {collectionName} will be replaced by the name of the collection.",
>         "message": "{collectionName} - (missing a level)"
> ```

see comment above for this one

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/231)* status: 9 of 13 files reviewed, 4 unresolved discussions (waiting on @hatton)

___
*[src/components/ByLevelGroups.tsx, line 77 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/231#-MNzi0fl2ukaTR7jVFFq:-MO3nCSg5fXpC1xH4WEf:b-896fix) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/076192cb285117b5ca655998c9b5b9033fad3ec4/src/components/ByLevelGroups.tsx#L77)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Hmm... like the one above ( myCollection - level 3) this can be instead be got at by combining the translation of the collection name with "-" and then a simple "(missing level)" string. Or just "Missing Level". Would need a description giving an example of how it is used.  Note I've purposefully dropped the "a".
</blockquote></details>

Done.
___
*[src/localization/Code Strings.json, line 80 at r2](https://reviewable.io/reviews/bloombooks/bloomlibrary2/231#-MO3cMlHE2b8cshi9fre:-MO3nDPX1g_5Avvtz8VL:b-896fix) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/13b9e8c6cf37b9ca5266d41c87dcf22346d5b859/src/localization/Code Strings.json#L80)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

see comment above for this one
</blockquote></details>

Done.

**Pull request merged**
