### PR TITLE
BL-8933 Installer link component

### PR DESCRIPTION
**Pull request by gmartin7**
* for CS version link

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/174)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/174)* status: all files reviewed, 3 unresolved discussions (waiting on @gmartin7)

___
*[src/components/ContentfulPage.tsx, line 62 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/174#-MK6HH3K87dLXCiilDUW:-MK6HH3K87dLXCiilDUX:bh198yi) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/2c9ad21b64d2ac68d6cd6a2f7f34513290ad9e56/src/components/ContentfulPage.tsx#L62)):*
> ```
> WindowsInstallLink
> ```
We better make this match the component name or we'll confuse ourselves.
___
*[src/components/WindowsInstallerLink.tsx, line 23 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/174#-MK6Hvl49BN0AVWOHWGR:-MK6Hvl49BN0AVWOHWGS:b-hbkckx) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/2c9ad21b64d2ac68d6cd6a2f7f34513290ad9e56/src/components/WindowsInstallerLink.tsx#L23)):*
> ```XML
>             ? versionRequest.response.data
>             : {};
>     const versionNumber = info.version ?? "0.0.0";
> ```

I don't like that everything above here is duplicated in WindowsInstallerDownloads.

If you want to take on extracting it, go for it.
But I won't force the issue.
___
*[src/components/WindowsInstallerLink.tsx, line 35 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/174#-MK6ILUL9PIXuN8Fmte-:-MK6ILUL9PIXuN8Fmte0:bjke363) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/2c9ad21b64d2ac68d6cd6a2f7f34513290ad9e56/src/components/WindowsInstallerLink.tsx#L35)):*
> ```XML
>                 `}
>             >
>                 {props.channel === "CS" &&
> ```

What is the benefit of this condition? We want it to work for any channel.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/174)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[src/components/ContentfulPage.tsx, line 62 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/174#-MK6HH3K87dLXCiilDUW:-MK6I_ti8zCeYClDtDXm:bglzsat) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/2c9ad21b64d2ac68d6cd6a2f7f34513290ad9e56/src/components/ContentfulPage.tsx#L62)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> WindowsInstallLink
> ```
We better make this match the component name or we'll confuse ourselves.

</blockquote></details>

I purposefully didn't... like the next one. (there's a plural difference there). But I could do it like that one.
___
*[src/components/WindowsInstallerLink.tsx, line 23 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/174#-MK6Hvl49BN0AVWOHWGR:-MK6_65Z7hqQ98Eki8Qi:b-onpc6b) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/2c9ad21b64d2ac68d6cd6a2f7f34513290ad9e56/src/components/WindowsInstallerLink.tsx#L23)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I don't like that everything above here is duplicated in WindowsInstallerDownloads.

If you want to take on extracting it, go for it.
But I won't force the issue.
</blockquote></details>

I did pull out a small function that could be a start for something better, if you want.
___
*[src/components/WindowsInstallerLink.tsx, line 35 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/174#-MK6ILUL9PIXuN8Fmte-:-MK6J9FhEC3MpWyhEbvu:bwragvn) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/2c9ad21b64d2ac68d6cd6a2f7f34513290ad9e56/src/components/WindowsInstallerLink.tsx#L35)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

What is the benefit of this condition? We want it to work for any channel.
</blockquote></details>

Done. (Removed/simplified)

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/174)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[src/components/ContentfulPage.tsx, line 62 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/174#-MK6HH3K87dLXCiilDUW:-MK6gstpE-EkIlk_Dx_a:b-mi8sfq) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/2c9ad21b64d2ac68d6cd6a2f7f34513290ad9e56/src/components/ContentfulPage.tsx#L62)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

I purposefully didn't... like the next one. (there's a plural difference there). But I could do it like that one.
</blockquote></details>

I'm pretty sure that was a mistake and likely to cause confusion in the future. Feel free to fix that one if you like, too.
___
*[src/components/WindowsInstallerLink.tsx, line 23 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/174#-MK6Hvl49BN0AVWOHWGR:-MK6h6L_7VmdnHs9vrcx:b-e3jfcl) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/2c9ad21b64d2ac68d6cd6a2f7f34513290ad9e56/src/components/WindowsInstallerLink.tsx#L23)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

I did pull out a small function that could be a start for something better, if you want.
</blockquote></details>

Go ahead and move the useAxios call in there, too.

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/174)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/components/ContentfulPage.tsx, line 62 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/174#-MK6HH3K87dLXCiilDUW:-MK6ksYmD6TLAca-XwPP:b-896fix) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/2c9ad21b64d2ac68d6cd6a2f7f34513290ad9e56/src/components/ContentfulPage.tsx#L62)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm pretty sure that was a mistake and likely to cause confusion in the future. Feel free to fix that one if you like, too.
</blockquote></details>

Done.
___
*[src/components/WindowsInstallerLink.tsx, line 23 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/174#-MK6Hvl49BN0AVWOHWGR:-MK6k7Fm1tsWXZZhidEE:b-vf25eb) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/2c9ad21b64d2ac68d6cd6a2f7f34513290ad9e56/src/components/WindowsInstallerLink.tsx#L23)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Go ahead and move the useAxios call in there, too.
</blockquote></details>

How? It must be used inside of a React FunctionalComponent.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/174)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/components/WindowsInstallerLink.tsx, line 23 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/174#-MK6Hvl49BN0AVWOHWGR:-MK6lZ8B-pdfn8MFsxPX:b-myxumx) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/2c9ad21b64d2ac68d6cd6a2f7f34513290ad9e56/src/components/WindowsInstallerLink.tsx#L23)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

How? It must be used inside of a React FunctionalComponent.
</blockquote></details>

Ah, yes.

**Pull request merged**
