### PR TITLE
BL-9601 improve styling of card hover

### PR DESCRIPTION
**Pull request by hatton**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/306)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
Looks good other than the prettier question.

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/306#-:-MUPUvroAHDc9Msc2GxE:b-36gkxl)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[src/components/Routes.tsx, line 44 at r1](https://reviewable.io/reviews/bloombooks/bloomlibrary2/306#-MUOtGhB7OGzhDiGA90x:-MUOtGhC24VBbeedVzEf:b-mmzhg6) ([raw file](https://github.com/bloombooks/bloomlibrary2/blob/a42ff2ed245594d1dae8bd73960f6bfd95a8d096/src/components/Routes.tsx#L44)):*
> ```XML
>             <ThemeForLocation urlKey={location.pathname}>
>                 <Switch>
>                 <Route
> ```

Is it possible your prettier isn't formatting on save? 
This line and some others should be indented one more.

**Review by hatton — COMMENTED** [review]
As happened last time you touched this file, the resulting diff was unreadable, so I did not commit those blocks.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/306#-:-MUQ-Fwy1AZH0L3qINpF:b-p6qzr4)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/306)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

**Review by andrew-polk — COMMENTED** [review]
I went ahead and let it format now that it is reviewed.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomlibrary2/306#-:-MUQJwbM7CQoOhqGXU9l:bsftrco)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

**Pull request merged**
