### PR TITLE
Enable Alpha Tiles links

### PR DESCRIPTION
**Pull request by hatton**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/560)

### CODE REVIEW

**Review by andrew-polk — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/560)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @hatton)

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/560)* status: 5 of 9 files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[`src/components/AlphaTilesButton.tsx` line 30 at r2](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/560#-O2_ltFQ57aCNiPlxezh:-O2_ltFQ57aCNiPlxezi:b-sx3xdg) ([raw file](https://github.com/BloomBooks/BloomLibrary2/blob/de8581abba8402f80342e3fda9f49c29fb1a6bb5/src/components/AlphaTilesButton.tsx#L30)):*
> ```XML
>     let googlePlayLogo = GooglePlayLogo_EN;
> 
>     if (language.includes("es")) {
> ```

Seems more accurate to use `startsWith`.
If there's some scenario you're thinking of where `includes` is better, it is probably worth a comment.

I'm not sure if we want to add logos for them... but we do have a fair bit of the code strings translated into Portuguese. And even some (much less) in Chinese.

**Comment by hatton** [comment]
*[`src/components/AlphaTilesButton.tsx` line 30 at r2](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/560#-O2_ltFQ57aCNiPlxezh:-O2aXdMl49CturiVZI8g:bvq24y2) ([raw file](https://github.com/BloomBooks/BloomLibrary2/blob/de8581abba8402f80342e3fda9f49c29fb1a6bb5/src/components/AlphaTilesButton.tsx#L30)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Seems more accurate to use `startsWith`.
If there's some scenario you're thinking of where `includes` is better, it is probably worth a comment.

I'm not sure if we want to add logos for them... but we do have a fair bit of the code strings translated into Portuguese. And even some (much less) in Chinese.
</blockquote></details>

Thanks, good catch.

On logos, I think I've reach my comfort level of adding logos to the bundle for now. We can always add more.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 4 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/560)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @hatton)

**Pull request merged**
